// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

/**
 * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ClientInitReq}
 */
public  final class ClientInitReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
    ClientInitReqOrBuilder {
  // Use ClientInitReq.newBuilder() to construct.
  private ClientInitReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientInitReq() {
    taskId_ = 0;
    totalSize_ = 0;
    targetDir_ = "";
    syncType_ = 0;
    fileBaseInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ClientInitReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            taskId_ = input.readInt32();
            break;
          }
          case 16: {

            totalSize_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            targetDir_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            syncType_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              fileBaseInfos_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.FileBaseInfo>();
              mutable_bitField0_ |= 0x00000010;
            }
            fileBaseInfos_.add(
                input.readMessage(cn.com.unary.initcopy.grpc.entity.FileBaseInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        fileBaseInfos_ = java.util.Collections.unmodifiableList(fileBaseInfos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.com.unary.initcopy.grpc.entity.ClientInitReq.class, cn.com.unary.initcopy.grpc.entity.ClientInitReq.Builder.class);
  }

  private int bitField0_;
  public static final int TASKID_FIELD_NUMBER = 1;
  private int taskId_;
  /**
   * <code>optional int32 taskId = 1;</code>
   */
  public int getTaskId() {
    return taskId_;
  }

  public static final int TOTALSIZE_FIELD_NUMBER = 2;
  private int totalSize_;
  /**
   * <pre>
   *总大小
   * </pre>
   *
   * <code>optional int32 totalSize = 2;</code>
   */
  public int getTotalSize() {
    return totalSize_;
  }

  public static final int TARGETDIR_FIELD_NUMBER = 3;
  private volatile java.lang.Object targetDir_;
  /**
   * <pre>
   *目标路径
   * </pre>
   *
   * <code>optional string targetDir = 3;</code>
   */
  public java.lang.String getTargetDir() {
    java.lang.Object ref = targetDir_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetDir_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *目标路径
   * </pre>
   *
   * <code>optional string targetDir = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTargetDirBytes() {
    java.lang.Object ref = targetDir_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYNCTYPE_FIELD_NUMBER = 4;
  private int syncType_;
  /**
   * <pre>
   * 同步方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
   */
  public int getSyncTypeValue() {
    return syncType_;
  }
  /**
   * <pre>
   * 同步方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
   */
  public cn.com.unary.initcopy.grpc.constant.SyncType getSyncType() {
    cn.com.unary.initcopy.grpc.constant.SyncType result = cn.com.unary.initcopy.grpc.constant.SyncType.valueOf(syncType_);
    return result == null ? cn.com.unary.initcopy.grpc.constant.SyncType.UNRECOGNIZED : result;
  }

  public static final int FILEBASEINFOS_FIELD_NUMBER = 5;
  private java.util.List<cn.com.unary.initcopy.grpc.entity.FileBaseInfo> fileBaseInfos_;
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
   */
  public java.util.List<cn.com.unary.initcopy.grpc.entity.FileBaseInfo> getFileBaseInfosList() {
    return fileBaseInfos_;
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
   */
  public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.FileBaseInfoOrBuilder> 
      getFileBaseInfosOrBuilderList() {
    return fileBaseInfos_;
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
   */
  public int getFileBaseInfosCount() {
    return fileBaseInfos_.size();
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.FileBaseInfo getFileBaseInfos(int index) {
    return fileBaseInfos_.get(index);
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.FileBaseInfoOrBuilder getFileBaseInfosOrBuilder(
      int index) {
    return fileBaseInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (taskId_ != 0) {
      output.writeInt32(1, taskId_);
    }
    if (totalSize_ != 0) {
      output.writeInt32(2, totalSize_);
    }
    if (!getTargetDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, targetDir_);
    }
    if (syncType_ != cn.com.unary.initcopy.grpc.constant.SyncType.SYNC_ALL.getNumber()) {
      output.writeEnum(4, syncType_);
    }
    for (int i = 0; i < fileBaseInfos_.size(); i++) {
      output.writeMessage(5, fileBaseInfos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (taskId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, taskId_);
    }
    if (totalSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalSize_);
    }
    if (!getTargetDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, targetDir_);
    }
    if (syncType_ != cn.com.unary.initcopy.grpc.constant.SyncType.SYNC_ALL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, syncType_);
    }
    for (int i = 0; i < fileBaseInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, fileBaseInfos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.unary.initcopy.grpc.entity.ClientInitReq)) {
      return super.equals(obj);
    }
    cn.com.unary.initcopy.grpc.entity.ClientInitReq other = (cn.com.unary.initcopy.grpc.entity.ClientInitReq) obj;

    boolean result = true;
    result = result && (getTaskId()
        == other.getTaskId());
    result = result && (getTotalSize()
        == other.getTotalSize());
    result = result && getTargetDir()
        .equals(other.getTargetDir());
    result = result && syncType_ == other.syncType_;
    result = result && getFileBaseInfosList()
        .equals(other.getFileBaseInfosList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId();
    hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSize();
    hash = (37 * hash) + TARGETDIR_FIELD_NUMBER;
    hash = (53 * hash) + getTargetDir().hashCode();
    hash = (37 * hash) + SYNCTYPE_FIELD_NUMBER;
    hash = (53 * hash) + syncType_;
    if (getFileBaseInfosCount() > 0) {
      hash = (37 * hash) + FILEBASEINFOS_FIELD_NUMBER;
      hash = (53 * hash) + getFileBaseInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.unary.initcopy.grpc.entity.ClientInitReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ClientInitReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
      cn.com.unary.initcopy.grpc.entity.ClientInitReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.unary.initcopy.grpc.entity.ClientInitReq.class, cn.com.unary.initcopy.grpc.entity.ClientInitReq.Builder.class);
    }

    // Construct using cn.com.unary.initcopy.grpc.entity.ClientInitReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFileBaseInfosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = 0;

      totalSize_ = 0;

      targetDir_ = "";

      syncType_ = 0;

      if (fileBaseInfosBuilder_ == null) {
        fileBaseInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        fileBaseInfosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_descriptor;
    }

    public cn.com.unary.initcopy.grpc.entity.ClientInitReq getDefaultInstanceForType() {
      return cn.com.unary.initcopy.grpc.entity.ClientInitReq.getDefaultInstance();
    }

    public cn.com.unary.initcopy.grpc.entity.ClientInitReq build() {
      cn.com.unary.initcopy.grpc.entity.ClientInitReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.com.unary.initcopy.grpc.entity.ClientInitReq buildPartial() {
      cn.com.unary.initcopy.grpc.entity.ClientInitReq result = new cn.com.unary.initcopy.grpc.entity.ClientInitReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.taskId_ = taskId_;
      result.totalSize_ = totalSize_;
      result.targetDir_ = targetDir_;
      result.syncType_ = syncType_;
      if (fileBaseInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          fileBaseInfos_ = java.util.Collections.unmodifiableList(fileBaseInfos_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.fileBaseInfos_ = fileBaseInfos_;
      } else {
        result.fileBaseInfos_ = fileBaseInfosBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.unary.initcopy.grpc.entity.ClientInitReq) {
        return mergeFrom((cn.com.unary.initcopy.grpc.entity.ClientInitReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.unary.initcopy.grpc.entity.ClientInitReq other) {
      if (other == cn.com.unary.initcopy.grpc.entity.ClientInitReq.getDefaultInstance()) return this;
      if (other.getTaskId() != 0) {
        setTaskId(other.getTaskId());
      }
      if (other.getTotalSize() != 0) {
        setTotalSize(other.getTotalSize());
      }
      if (!other.getTargetDir().isEmpty()) {
        targetDir_ = other.targetDir_;
        onChanged();
      }
      if (other.syncType_ != 0) {
        setSyncTypeValue(other.getSyncTypeValue());
      }
      if (fileBaseInfosBuilder_ == null) {
        if (!other.fileBaseInfos_.isEmpty()) {
          if (fileBaseInfos_.isEmpty()) {
            fileBaseInfos_ = other.fileBaseInfos_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFileBaseInfosIsMutable();
            fileBaseInfos_.addAll(other.fileBaseInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.fileBaseInfos_.isEmpty()) {
          if (fileBaseInfosBuilder_.isEmpty()) {
            fileBaseInfosBuilder_.dispose();
            fileBaseInfosBuilder_ = null;
            fileBaseInfos_ = other.fileBaseInfos_;
            bitField0_ = (bitField0_ & ~0x00000010);
            fileBaseInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFileBaseInfosFieldBuilder() : null;
          } else {
            fileBaseInfosBuilder_.addAllMessages(other.fileBaseInfos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.com.unary.initcopy.grpc.entity.ClientInitReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.com.unary.initcopy.grpc.entity.ClientInitReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int taskId_ ;
    /**
     * <code>optional int32 taskId = 1;</code>
     */
    public int getTaskId() {
      return taskId_;
    }
    /**
     * <code>optional int32 taskId = 1;</code>
     */
    public Builder setTaskId(int value) {
      
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 taskId = 1;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = 0;
      onChanged();
      return this;
    }

    private int totalSize_ ;
    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional int32 totalSize = 2;</code>
     */
    public int getTotalSize() {
      return totalSize_;
    }
    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional int32 totalSize = 2;</code>
     */
    public Builder setTotalSize(int value) {
      
      totalSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional int32 totalSize = 2;</code>
     */
    public Builder clearTotalSize() {
      
      totalSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object targetDir_ = "";
    /**
     * <pre>
     *目标路径
     * </pre>
     *
     * <code>optional string targetDir = 3;</code>
     */
    public java.lang.String getTargetDir() {
      java.lang.Object ref = targetDir_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetDir_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *目标路径
     * </pre>
     *
     * <code>optional string targetDir = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTargetDirBytes() {
      java.lang.Object ref = targetDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *目标路径
     * </pre>
     *
     * <code>optional string targetDir = 3;</code>
     */
    public Builder setTargetDir(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标路径
     * </pre>
     *
     * <code>optional string targetDir = 3;</code>
     */
    public Builder clearTargetDir() {
      
      targetDir_ = getDefaultInstance().getTargetDir();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标路径
     * </pre>
     *
     * <code>optional string targetDir = 3;</code>
     */
    public Builder setTargetDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetDir_ = value;
      onChanged();
      return this;
    }

    private int syncType_ = 0;
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public int getSyncTypeValue() {
      return syncType_;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public Builder setSyncTypeValue(int value) {
      syncType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.constant.SyncType getSyncType() {
      cn.com.unary.initcopy.grpc.constant.SyncType result = cn.com.unary.initcopy.grpc.constant.SyncType.valueOf(syncType_);
      return result == null ? cn.com.unary.initcopy.grpc.constant.SyncType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public Builder setSyncType(cn.com.unary.initcopy.grpc.constant.SyncType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      syncType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public Builder clearSyncType() {
      
      syncType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<cn.com.unary.initcopy.grpc.entity.FileBaseInfo> fileBaseInfos_ =
      java.util.Collections.emptyList();
    private void ensureFileBaseInfosIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        fileBaseInfos_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.FileBaseInfo>(fileBaseInfos_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.FileBaseInfo, cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder, cn.com.unary.initcopy.grpc.entity.FileBaseInfoOrBuilder> fileBaseInfosBuilder_;

    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.FileBaseInfo> getFileBaseInfosList() {
      if (fileBaseInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fileBaseInfos_);
      } else {
        return fileBaseInfosBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public int getFileBaseInfosCount() {
      if (fileBaseInfosBuilder_ == null) {
        return fileBaseInfos_.size();
      } else {
        return fileBaseInfosBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.FileBaseInfo getFileBaseInfos(int index) {
      if (fileBaseInfosBuilder_ == null) {
        return fileBaseInfos_.get(index);
      } else {
        return fileBaseInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder setFileBaseInfos(
        int index, cn.com.unary.initcopy.grpc.entity.FileBaseInfo value) {
      if (fileBaseInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileBaseInfosIsMutable();
        fileBaseInfos_.set(index, value);
        onChanged();
      } else {
        fileBaseInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder setFileBaseInfos(
        int index, cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder builderForValue) {
      if (fileBaseInfosBuilder_ == null) {
        ensureFileBaseInfosIsMutable();
        fileBaseInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        fileBaseInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder addFileBaseInfos(cn.com.unary.initcopy.grpc.entity.FileBaseInfo value) {
      if (fileBaseInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileBaseInfosIsMutable();
        fileBaseInfos_.add(value);
        onChanged();
      } else {
        fileBaseInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder addFileBaseInfos(
        int index, cn.com.unary.initcopy.grpc.entity.FileBaseInfo value) {
      if (fileBaseInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileBaseInfosIsMutable();
        fileBaseInfos_.add(index, value);
        onChanged();
      } else {
        fileBaseInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder addFileBaseInfos(
        cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder builderForValue) {
      if (fileBaseInfosBuilder_ == null) {
        ensureFileBaseInfosIsMutable();
        fileBaseInfos_.add(builderForValue.build());
        onChanged();
      } else {
        fileBaseInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder addFileBaseInfos(
        int index, cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder builderForValue) {
      if (fileBaseInfosBuilder_ == null) {
        ensureFileBaseInfosIsMutable();
        fileBaseInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        fileBaseInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder addAllFileBaseInfos(
        java.lang.Iterable<? extends cn.com.unary.initcopy.grpc.entity.FileBaseInfo> values) {
      if (fileBaseInfosBuilder_ == null) {
        ensureFileBaseInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fileBaseInfos_);
        onChanged();
      } else {
        fileBaseInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder clearFileBaseInfos() {
      if (fileBaseInfosBuilder_ == null) {
        fileBaseInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        fileBaseInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public Builder removeFileBaseInfos(int index) {
      if (fileBaseInfosBuilder_ == null) {
        ensureFileBaseInfosIsMutable();
        fileBaseInfos_.remove(index);
        onChanged();
      } else {
        fileBaseInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder getFileBaseInfosBuilder(
        int index) {
      return getFileBaseInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.FileBaseInfoOrBuilder getFileBaseInfosOrBuilder(
        int index) {
      if (fileBaseInfosBuilder_ == null) {
        return fileBaseInfos_.get(index);  } else {
        return fileBaseInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.FileBaseInfoOrBuilder> 
         getFileBaseInfosOrBuilderList() {
      if (fileBaseInfosBuilder_ != null) {
        return fileBaseInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fileBaseInfos_);
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder addFileBaseInfosBuilder() {
      return getFileBaseInfosFieldBuilder().addBuilder(
          cn.com.unary.initcopy.grpc.entity.FileBaseInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder addFileBaseInfosBuilder(
        int index) {
      return getFileBaseInfosFieldBuilder().addBuilder(
          index, cn.com.unary.initcopy.grpc.entity.FileBaseInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.FileBaseInfo fileBaseInfos = 5;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder> 
         getFileBaseInfosBuilderList() {
      return getFileBaseInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.FileBaseInfo, cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder, cn.com.unary.initcopy.grpc.entity.FileBaseInfoOrBuilder> 
        getFileBaseInfosFieldBuilder() {
      if (fileBaseInfosBuilder_ == null) {
        fileBaseInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.com.unary.initcopy.grpc.entity.FileBaseInfo, cn.com.unary.initcopy.grpc.entity.FileBaseInfo.Builder, cn.com.unary.initcopy.grpc.entity.FileBaseInfoOrBuilder>(
                fileBaseInfos_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        fileBaseInfos_ = null;
      }
      return fileBaseInfosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
  }

  // @@protoc_insertion_point(class_scope:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
  private static final cn.com.unary.initcopy.grpc.entity.ClientInitReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.unary.initcopy.grpc.entity.ClientInitReq();
  }

  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientInitReq>
      PARSER = new com.google.protobuf.AbstractParser<ClientInitReq>() {
    public ClientInitReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientInitReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientInitReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientInitReq> getParserForType() {
    return PARSER;
  }

  public cn.com.unary.initcopy.grpc.entity.ClientInitReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

