// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_control_entity.proto

package cn.com.unary.initcopy.grpc.entity;

/**
 * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ClientInitReq}
 */
public  final class ClientInitReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
    ClientInitReqOrBuilder {
  // Use ClientInitReq.newBuilder() to construct.
  private ClientInitReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientInitReq() {
    taskId_ = "";
    totalSize_ = "";
    backUpPath_ = "";
    syncType_ = 0;
    baseFileInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ClientInitReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            totalSize_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            backUpPath_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            syncType_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              baseFileInfos_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.BaseFileInfo>();
              mutable_bitField0_ |= 0x00000010;
            }
            baseFileInfos_.add(
                input.readMessage(cn.com.unary.initcopy.grpc.entity.BaseFileInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        baseFileInfos_ = java.util.Collections.unmodifiableList(baseFileInfos_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.entity.TC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.com.unary.initcopy.grpc.entity.TC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.com.unary.initcopy.grpc.entity.ClientInitReq.class, cn.com.unary.initcopy.grpc.entity.ClientInitReq.Builder.class);
  }

  private int bitField0_;
  public static final int TASKID_FIELD_NUMBER = 1;
  private volatile java.lang.Object taskId_;
  /**
   * <code>optional string taskId = 1;</code>
   */
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string taskId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTALSIZE_FIELD_NUMBER = 2;
  private volatile java.lang.Object totalSize_;
  /**
   * <pre>
   *总大小
   * </pre>
   *
   * <code>optional string totalSize = 2;</code>
   */
  public java.lang.String getTotalSize() {
    java.lang.Object ref = totalSize_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalSize_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *总大小
   * </pre>
   *
   * <code>optional string totalSize = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTotalSizeBytes() {
    java.lang.Object ref = totalSize_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalSize_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BACKUPPATH_FIELD_NUMBER = 3;
  private volatile java.lang.Object backUpPath_;
  /**
   * <pre>
   * 备份的目标端路径
   * </pre>
   *
   * <code>optional string backUpPath = 3;</code>
   */
  public java.lang.String getBackUpPath() {
    java.lang.Object ref = backUpPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backUpPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 备份的目标端路径
   * </pre>
   *
   * <code>optional string backUpPath = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBackUpPathBytes() {
    java.lang.Object ref = backUpPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backUpPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYNCTYPE_FIELD_NUMBER = 4;
  private int syncType_;
  /**
   * <pre>
   * 同步方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
   */
  public int getSyncTypeValue() {
    return syncType_;
  }
  /**
   * <pre>
   * 同步方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
   */
  public cn.com.unary.initcopy.grpc.constant.SyncType getSyncType() {
    cn.com.unary.initcopy.grpc.constant.SyncType result = cn.com.unary.initcopy.grpc.constant.SyncType.valueOf(syncType_);
    return result == null ? cn.com.unary.initcopy.grpc.constant.SyncType.UNRECOGNIZED : result;
  }

  public static final int BASEFILEINFOS_FIELD_NUMBER = 5;
  private java.util.List<cn.com.unary.initcopy.grpc.entity.BaseFileInfo> baseFileInfos_;
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
   */
  public java.util.List<cn.com.unary.initcopy.grpc.entity.BaseFileInfo> getBaseFileInfosList() {
    return baseFileInfos_;
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
   */
  public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.BaseFileInfoOrBuilder> 
      getBaseFileInfosOrBuilderList() {
    return baseFileInfos_;
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
   */
  public int getBaseFileInfosCount() {
    return baseFileInfos_.size();
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.BaseFileInfo getBaseFileInfos(int index) {
    return baseFileInfos_.get(index);
  }
  /**
   * <pre>
   * 文件信息
   * </pre>
   *
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.BaseFileInfoOrBuilder getBaseFileInfosOrBuilder(
      int index) {
    return baseFileInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
    }
    if (!getTotalSizeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, totalSize_);
    }
    if (!getBackUpPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, backUpPath_);
    }
    if (syncType_ != cn.com.unary.initcopy.grpc.constant.SyncType.SYNC_ALL.getNumber()) {
      output.writeEnum(4, syncType_);
    }
    for (int i = 0; i < baseFileInfos_.size(); i++) {
      output.writeMessage(5, baseFileInfos_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
    }
    if (!getTotalSizeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, totalSize_);
    }
    if (!getBackUpPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, backUpPath_);
    }
    if (syncType_ != cn.com.unary.initcopy.grpc.constant.SyncType.SYNC_ALL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, syncType_);
    }
    for (int i = 0; i < baseFileInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, baseFileInfos_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.unary.initcopy.grpc.entity.ClientInitReq)) {
      return super.equals(obj);
    }
    cn.com.unary.initcopy.grpc.entity.ClientInitReq other = (cn.com.unary.initcopy.grpc.entity.ClientInitReq) obj;

    boolean result = true;
    result = result && getTaskId()
        .equals(other.getTaskId());
    result = result && getTotalSize()
        .equals(other.getTotalSize());
    result = result && getBackUpPath()
        .equals(other.getBackUpPath());
    result = result && syncType_ == other.syncType_;
    result = result && getBaseFileInfosList()
        .equals(other.getBaseFileInfosList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSize().hashCode();
    hash = (37 * hash) + BACKUPPATH_FIELD_NUMBER;
    hash = (53 * hash) + getBackUpPath().hashCode();
    hash = (37 * hash) + SYNCTYPE_FIELD_NUMBER;
    hash = (53 * hash) + syncType_;
    if (getBaseFileInfosCount() > 0) {
      hash = (37 * hash) + BASEFILEINFOS_FIELD_NUMBER;
      hash = (53 * hash) + getBaseFileInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.unary.initcopy.grpc.entity.ClientInitReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ClientInitReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
      cn.com.unary.initcopy.grpc.entity.ClientInitReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.unary.initcopy.grpc.entity.TC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.unary.initcopy.grpc.entity.TC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.unary.initcopy.grpc.entity.ClientInitReq.class, cn.com.unary.initcopy.grpc.entity.ClientInitReq.Builder.class);
    }

    // Construct using cn.com.unary.initcopy.grpc.entity.ClientInitReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBaseFileInfosFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = "";

      totalSize_ = "";

      backUpPath_ = "";

      syncType_ = 0;

      if (baseFileInfosBuilder_ == null) {
        baseFileInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        baseFileInfosBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.unary.initcopy.grpc.entity.TC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ClientInitReq_descriptor;
    }

    public cn.com.unary.initcopy.grpc.entity.ClientInitReq getDefaultInstanceForType() {
      return cn.com.unary.initcopy.grpc.entity.ClientInitReq.getDefaultInstance();
    }

    public cn.com.unary.initcopy.grpc.entity.ClientInitReq build() {
      cn.com.unary.initcopy.grpc.entity.ClientInitReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.com.unary.initcopy.grpc.entity.ClientInitReq buildPartial() {
      cn.com.unary.initcopy.grpc.entity.ClientInitReq result = new cn.com.unary.initcopy.grpc.entity.ClientInitReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.taskId_ = taskId_;
      result.totalSize_ = totalSize_;
      result.backUpPath_ = backUpPath_;
      result.syncType_ = syncType_;
      if (baseFileInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          baseFileInfos_ = java.util.Collections.unmodifiableList(baseFileInfos_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.baseFileInfos_ = baseFileInfos_;
      } else {
        result.baseFileInfos_ = baseFileInfosBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.unary.initcopy.grpc.entity.ClientInitReq) {
        return mergeFrom((cn.com.unary.initcopy.grpc.entity.ClientInitReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.unary.initcopy.grpc.entity.ClientInitReq other) {
      if (other == cn.com.unary.initcopy.grpc.entity.ClientInitReq.getDefaultInstance()) return this;
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (!other.getTotalSize().isEmpty()) {
        totalSize_ = other.totalSize_;
        onChanged();
      }
      if (!other.getBackUpPath().isEmpty()) {
        backUpPath_ = other.backUpPath_;
        onChanged();
      }
      if (other.syncType_ != 0) {
        setSyncTypeValue(other.getSyncTypeValue());
      }
      if (baseFileInfosBuilder_ == null) {
        if (!other.baseFileInfos_.isEmpty()) {
          if (baseFileInfos_.isEmpty()) {
            baseFileInfos_ = other.baseFileInfos_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureBaseFileInfosIsMutable();
            baseFileInfos_.addAll(other.baseFileInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.baseFileInfos_.isEmpty()) {
          if (baseFileInfosBuilder_.isEmpty()) {
            baseFileInfosBuilder_.dispose();
            baseFileInfosBuilder_ = null;
            baseFileInfos_ = other.baseFileInfos_;
            bitField0_ = (bitField0_ & ~0x00000010);
            baseFileInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBaseFileInfosFieldBuilder() : null;
          } else {
            baseFileInfosBuilder_.addAllMessages(other.baseFileInfos_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.com.unary.initcopy.grpc.entity.ClientInitReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.com.unary.initcopy.grpc.entity.ClientInitReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object taskId_ = "";
    /**
     * <code>optional string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string taskId = 1;</code>
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      taskId_ = value;
      onChanged();
      return this;
    }

      /**
       * <code>optional string taskId = 1;</code>
       */
      public Builder setTaskId(
              java.lang.String value) {
          if (value == null) {
              throw new NullPointerException();
          }

          taskId_ = value;
          onChanged();
          return this;
      }

    /**
     * <code>optional string taskId = 1;</code>
     */
    public Builder clearTaskId() {

      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }

    private java.lang.Object totalSize_ = "";
    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional string totalSize = 2;</code>
     */
    public java.lang.String getTotalSize() {
      java.lang.Object ref = totalSize_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalSize_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional string totalSize = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTotalSizeBytes() {
      java.lang.Object ref = totalSize_;
      if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional string totalSize = 2;</code>
     */
    public Builder setTotalSizeBytes(
            com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        totalSize_ = value;
        onChanged();
        return this;
    }

      /**
       * <pre>
       * 总大小
       * </pre>
       *
       * <code>optional string totalSize = 2;</code>
       */
      public Builder setTotalSize(
              java.lang.String value) {
          if (value == null) {
              throw new NullPointerException();
          }

          totalSize_ = value;
          onChanged();
          return this;
      }

    /**
     * <pre>
     *总大小
     * </pre>
     *
     * <code>optional string totalSize = 2;</code>
     */
    public Builder clearTotalSize() {

      totalSize_ = getDefaultInstance().getTotalSize();
      onChanged();
      return this;
    }

    private java.lang.Object backUpPath_ = "";
    /**
     * <pre>
     * 备份的目标端路径
     * </pre>
     *
     * <code>optional string backUpPath = 3;</code>
     */
    public java.lang.String getBackUpPath() {
      java.lang.Object ref = backUpPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backUpPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 备份的目标端路径
     * </pre>
     *
     * <code>optional string backUpPath = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBackUpPathBytes() {
      java.lang.Object ref = backUpPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backUpPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 备份的目标端路径
     * </pre>
     *
     * <code>optional string backUpPath = 3;</code>
     */
    public Builder setBackUpPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      backUpPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 备份的目标端路径
     * </pre>
     *
     * <code>optional string backUpPath = 3;</code>
     */
    public Builder clearBackUpPath() {
      
      backUpPath_ = getDefaultInstance().getBackUpPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 备份的目标端路径
     * </pre>
     *
     * <code>optional string backUpPath = 3;</code>
     */
    public Builder setBackUpPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      backUpPath_ = value;
      onChanged();
      return this;
    }

    private int syncType_ = 0;
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public int getSyncTypeValue() {
      return syncType_;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public Builder setSyncTypeValue(int value) {
      syncType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.constant.SyncType getSyncType() {
      cn.com.unary.initcopy.grpc.constant.SyncType result = cn.com.unary.initcopy.grpc.constant.SyncType.valueOf(syncType_);
      return result == null ? cn.com.unary.initcopy.grpc.constant.SyncType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public Builder setSyncType(cn.com.unary.initcopy.grpc.constant.SyncType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      syncType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 4;</code>
     */
    public Builder clearSyncType() {
      
      syncType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<cn.com.unary.initcopy.grpc.entity.BaseFileInfo> baseFileInfos_ =
      java.util.Collections.emptyList();
    private void ensureBaseFileInfosIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        baseFileInfos_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.BaseFileInfo>(baseFileInfos_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.BaseFileInfo, cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder, cn.com.unary.initcopy.grpc.entity.BaseFileInfoOrBuilder> baseFileInfosBuilder_;

    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.BaseFileInfo> getBaseFileInfosList() {
      if (baseFileInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(baseFileInfos_);
      } else {
        return baseFileInfosBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public int getBaseFileInfosCount() {
      if (baseFileInfosBuilder_ == null) {
        return baseFileInfos_.size();
      } else {
        return baseFileInfosBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.BaseFileInfo getBaseFileInfos(int index) {
      if (baseFileInfosBuilder_ == null) {
        return baseFileInfos_.get(index);
      } else {
        return baseFileInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder setBaseFileInfos(
        int index, cn.com.unary.initcopy.grpc.entity.BaseFileInfo value) {
      if (baseFileInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBaseFileInfosIsMutable();
        baseFileInfos_.set(index, value);
        onChanged();
      } else {
        baseFileInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder setBaseFileInfos(
        int index, cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder builderForValue) {
      if (baseFileInfosBuilder_ == null) {
        ensureBaseFileInfosIsMutable();
        baseFileInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        baseFileInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder addBaseFileInfos(cn.com.unary.initcopy.grpc.entity.BaseFileInfo value) {
      if (baseFileInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBaseFileInfosIsMutable();
        baseFileInfos_.add(value);
        onChanged();
      } else {
        baseFileInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder addBaseFileInfos(
        int index, cn.com.unary.initcopy.grpc.entity.BaseFileInfo value) {
      if (baseFileInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBaseFileInfosIsMutable();
        baseFileInfos_.add(index, value);
        onChanged();
      } else {
        baseFileInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder addBaseFileInfos(
        cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder builderForValue) {
      if (baseFileInfosBuilder_ == null) {
        ensureBaseFileInfosIsMutable();
        baseFileInfos_.add(builderForValue.build());
        onChanged();
      } else {
        baseFileInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder addBaseFileInfos(
        int index, cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder builderForValue) {
      if (baseFileInfosBuilder_ == null) {
        ensureBaseFileInfosIsMutable();
        baseFileInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        baseFileInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder addAllBaseFileInfos(
        java.lang.Iterable<? extends cn.com.unary.initcopy.grpc.entity.BaseFileInfo> values) {
      if (baseFileInfosBuilder_ == null) {
        ensureBaseFileInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, baseFileInfos_);
        onChanged();
      } else {
        baseFileInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder clearBaseFileInfos() {
      if (baseFileInfosBuilder_ == null) {
        baseFileInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        baseFileInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public Builder removeBaseFileInfos(int index) {
      if (baseFileInfosBuilder_ == null) {
        ensureBaseFileInfosIsMutable();
        baseFileInfos_.remove(index);
        onChanged();
      } else {
        baseFileInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder getBaseFileInfosBuilder(
        int index) {
      return getBaseFileInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.BaseFileInfoOrBuilder getBaseFileInfosOrBuilder(
        int index) {
      if (baseFileInfosBuilder_ == null) {
        return baseFileInfos_.get(index);  } else {
        return baseFileInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.BaseFileInfoOrBuilder> 
         getBaseFileInfosOrBuilderList() {
      if (baseFileInfosBuilder_ != null) {
        return baseFileInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(baseFileInfos_);
      }
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder addBaseFileInfosBuilder() {
      return getBaseFileInfosFieldBuilder().addBuilder(
          cn.com.unary.initcopy.grpc.entity.BaseFileInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder addBaseFileInfosBuilder(
        int index) {
      return getBaseFileInfosFieldBuilder().addBuilder(
          index, cn.com.unary.initcopy.grpc.entity.BaseFileInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 文件信息
     * </pre>
     *
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.BaseFileInfo baseFileInfos = 5;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder> 
         getBaseFileInfosBuilderList() {
      return getBaseFileInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.BaseFileInfo, cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder, cn.com.unary.initcopy.grpc.entity.BaseFileInfoOrBuilder> 
        getBaseFileInfosFieldBuilder() {
      if (baseFileInfosBuilder_ == null) {
        baseFileInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.com.unary.initcopy.grpc.entity.BaseFileInfo, cn.com.unary.initcopy.grpc.entity.BaseFileInfo.Builder, cn.com.unary.initcopy.grpc.entity.BaseFileInfoOrBuilder>(
                baseFileInfos_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        baseFileInfos_ = null;
      }
      return baseFileInfosBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
  }

  // @@protoc_insertion_point(class_scope:cn.com.unary.initcopy.grpc.entity.ClientInitReq)
  private static final cn.com.unary.initcopy.grpc.entity.ClientInitReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.unary.initcopy.grpc.entity.ClientInitReq();
  }

  public static cn.com.unary.initcopy.grpc.entity.ClientInitReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientInitReq>
      PARSER = new com.google.protobuf.AbstractParser<ClientInitReq>() {
    public ClientInitReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientInitReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientInitReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientInitReq> getParserForType() {
    return PARSER;
  }

  public cn.com.unary.initcopy.grpc.entity.ClientInitReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

