// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_control_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface DiffFileChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.DiffFileChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 强校验码Md5
   * </pre>
   *
   * <code>optional string strongCheckCode = 1;</code>
   */
  java.lang.String getStrongCheckCode();
  /**
   * <pre>
   * 强校验码Md5
   * </pre>
   *
   * <code>optional string strongCheckCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getStrongCheckCodeBytes();

  /**
   * <pre>
   * 弱校验码 CRC
   * </pre>
   *
   * <code>optional string weakCheckCode = 2;</code>
   */
  java.lang.String getWeakCheckCode();
  /**
   * <pre>
   * 弱校验码 CRC
   * </pre>
   *
   * <code>optional string weakCheckCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getWeakCheckCodeBytes();

  /**
   * <pre>
   * 块序号
   * </pre>
   *
   * <code>optional string chunkSeq = 3;</code>
   */
  java.lang.String getChunkSeq();
  /**
   * <pre>
   * 块序号
   * </pre>
   *
   * <code>optional string chunkSeq = 3;</code>
   */
  com.google.protobuf.ByteString
      getChunkSeqBytes();
}
