// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface DiffFileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.DiffFileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文件Id
   * </pre>
   *
   * <code>optional string fileId = 1;</code>
   */
  java.lang.String getFileId();
  /**
   * <pre>
   * 文件Id
   * </pre>
   *
   * <code>optional string fileId = 1;</code>
   */
  com.google.protobuf.ByteString
      getFileIdBytes();

  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileChunk> 
      getDiffFileChunkList();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  cn.com.unary.initcopy.grpc.entity.DiffFileChunk getDiffFileChunk(int index);
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  int getDiffFileChunkCount();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  java.util.List<? extends cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder> 
      getDiffFileChunkOrBuilderList();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder getDiffFileChunkOrBuilder(
      int index);
}
