// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

/**
 * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.DiffFileInfo}
 */
public  final class DiffFileInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.unary.initcopy.grpc.entity.DiffFileInfo)
    DiffFileInfoOrBuilder {
  // Use DiffFileInfo.newBuilder() to construct.
  private DiffFileInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DiffFileInfo() {
    fileId_ = "";
    diffFileChunk_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DiffFileInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fileId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              diffFileChunk_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.DiffFileChunk>();
              mutable_bitField0_ |= 0x00000002;
            }
            diffFileChunk_.add(
                input.readMessage(cn.com.unary.initcopy.grpc.entity.DiffFileChunk.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        diffFileChunk_ = java.util.Collections.unmodifiableList(diffFileChunk_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_DiffFileInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_DiffFileInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.com.unary.initcopy.grpc.entity.DiffFileInfo.class, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder.class);
  }

  private int bitField0_;
  public static final int FILEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object fileId_;
  /**
   * <pre>
   * 文件Id
   * </pre>
   *
   * <code>optional string fileId = 1;</code>
   */
  public java.lang.String getFileId() {
    java.lang.Object ref = fileId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文件Id
   * </pre>
   *
   * <code>optional string fileId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFileIdBytes() {
    java.lang.Object ref = fileId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIFFFILECHUNK_FIELD_NUMBER = 2;
  private java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileChunk> diffFileChunk_;
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  public java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileChunk> getDiffFileChunkList() {
    return diffFileChunk_;
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder> 
      getDiffFileChunkOrBuilderList() {
    return diffFileChunk_;
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  public int getDiffFileChunkCount() {
    return diffFileChunk_.size();
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.DiffFileChunk getDiffFileChunk(int index) {
    return diffFileChunk_.get(index);
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder getDiffFileChunkOrBuilder(
      int index) {
    return diffFileChunk_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFileIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileId_);
    }
    for (int i = 0; i < diffFileChunk_.size(); i++) {
      output.writeMessage(2, diffFileChunk_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileId_);
    }
    for (int i = 0; i < diffFileChunk_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, diffFileChunk_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.unary.initcopy.grpc.entity.DiffFileInfo)) {
      return super.equals(obj);
    }
    cn.com.unary.initcopy.grpc.entity.DiffFileInfo other = (cn.com.unary.initcopy.grpc.entity.DiffFileInfo) obj;

    boolean result = true;
    result = result && getFileId()
        .equals(other.getFileId());
    result = result && getDiffFileChunkList()
        .equals(other.getDiffFileChunkList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + FILEID_FIELD_NUMBER;
    hash = (53 * hash) + getFileId().hashCode();
    if (getDiffFileChunkCount() > 0) {
      hash = (37 * hash) + DIFFFILECHUNK_FIELD_NUMBER;
      hash = (53 * hash) + getDiffFileChunkList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.unary.initcopy.grpc.entity.DiffFileInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.DiffFileInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.unary.initcopy.grpc.entity.DiffFileInfo)
      cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_DiffFileInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_DiffFileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.unary.initcopy.grpc.entity.DiffFileInfo.class, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder.class);
    }

    // Construct using cn.com.unary.initcopy.grpc.entity.DiffFileInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDiffFileChunkFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      fileId_ = "";

      if (diffFileChunkBuilder_ == null) {
        diffFileChunk_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        diffFileChunkBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_DiffFileInfo_descriptor;
    }

    public cn.com.unary.initcopy.grpc.entity.DiffFileInfo getDefaultInstanceForType() {
      return cn.com.unary.initcopy.grpc.entity.DiffFileInfo.getDefaultInstance();
    }

    public cn.com.unary.initcopy.grpc.entity.DiffFileInfo build() {
      cn.com.unary.initcopy.grpc.entity.DiffFileInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.com.unary.initcopy.grpc.entity.DiffFileInfo buildPartial() {
      cn.com.unary.initcopy.grpc.entity.DiffFileInfo result = new cn.com.unary.initcopy.grpc.entity.DiffFileInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.fileId_ = fileId_;
      if (diffFileChunkBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          diffFileChunk_ = java.util.Collections.unmodifiableList(diffFileChunk_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.diffFileChunk_ = diffFileChunk_;
      } else {
        result.diffFileChunk_ = diffFileChunkBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.unary.initcopy.grpc.entity.DiffFileInfo) {
        return mergeFrom((cn.com.unary.initcopy.grpc.entity.DiffFileInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.unary.initcopy.grpc.entity.DiffFileInfo other) {
      if (other == cn.com.unary.initcopy.grpc.entity.DiffFileInfo.getDefaultInstance()) return this;
      if (!other.getFileId().isEmpty()) {
        fileId_ = other.fileId_;
        onChanged();
      }
      if (diffFileChunkBuilder_ == null) {
        if (!other.diffFileChunk_.isEmpty()) {
          if (diffFileChunk_.isEmpty()) {
            diffFileChunk_ = other.diffFileChunk_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDiffFileChunkIsMutable();
            diffFileChunk_.addAll(other.diffFileChunk_);
          }
          onChanged();
        }
      } else {
        if (!other.diffFileChunk_.isEmpty()) {
          if (diffFileChunkBuilder_.isEmpty()) {
            diffFileChunkBuilder_.dispose();
            diffFileChunkBuilder_ = null;
            diffFileChunk_ = other.diffFileChunk_;
            bitField0_ = (bitField0_ & ~0x00000002);
            diffFileChunkBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDiffFileChunkFieldBuilder() : null;
          } else {
            diffFileChunkBuilder_.addAllMessages(other.diffFileChunk_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.com.unary.initcopy.grpc.entity.DiffFileInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.com.unary.initcopy.grpc.entity.DiffFileInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object fileId_ = "";
    /**
     * <pre>
     * 文件Id
     * </pre>
     *
     * <code>optional string fileId = 1;</code>
     */
    public java.lang.String getFileId() {
      java.lang.Object ref = fileId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文件Id
     * </pre>
     *
     * <code>optional string fileId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      java.lang.Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文件Id
     * </pre>
     *
     * <code>optional string fileId = 1;</code>
     */
    public Builder setFileId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件Id
     * </pre>
     *
     * <code>optional string fileId = 1;</code>
     */
    public Builder clearFileId() {
      
      fileId_ = getDefaultInstance().getFileId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文件Id
     * </pre>
     *
     * <code>optional string fileId = 1;</code>
     */
    public Builder setFileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileChunk> diffFileChunk_ =
      java.util.Collections.emptyList();
    private void ensureDiffFileChunkIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        diffFileChunk_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.DiffFileChunk>(diffFileChunk_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.DiffFileChunk, cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder, cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder> diffFileChunkBuilder_;

    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileChunk> getDiffFileChunkList() {
      if (diffFileChunkBuilder_ == null) {
        return java.util.Collections.unmodifiableList(diffFileChunk_);
      } else {
        return diffFileChunkBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public int getDiffFileChunkCount() {
      if (diffFileChunkBuilder_ == null) {
        return diffFileChunk_.size();
      } else {
        return diffFileChunkBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileChunk getDiffFileChunk(int index) {
      if (diffFileChunkBuilder_ == null) {
        return diffFileChunk_.get(index);
      } else {
        return diffFileChunkBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder setDiffFileChunk(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileChunk value) {
      if (diffFileChunkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffFileChunkIsMutable();
        diffFileChunk_.set(index, value);
        onChanged();
      } else {
        diffFileChunkBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder setDiffFileChunk(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder builderForValue) {
      if (diffFileChunkBuilder_ == null) {
        ensureDiffFileChunkIsMutable();
        diffFileChunk_.set(index, builderForValue.build());
        onChanged();
      } else {
        diffFileChunkBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder addDiffFileChunk(cn.com.unary.initcopy.grpc.entity.DiffFileChunk value) {
      if (diffFileChunkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffFileChunkIsMutable();
        diffFileChunk_.add(value);
        onChanged();
      } else {
        diffFileChunkBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder addDiffFileChunk(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileChunk value) {
      if (diffFileChunkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffFileChunkIsMutable();
        diffFileChunk_.add(index, value);
        onChanged();
      } else {
        diffFileChunkBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder addDiffFileChunk(
        cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder builderForValue) {
      if (diffFileChunkBuilder_ == null) {
        ensureDiffFileChunkIsMutable();
        diffFileChunk_.add(builderForValue.build());
        onChanged();
      } else {
        diffFileChunkBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder addDiffFileChunk(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder builderForValue) {
      if (diffFileChunkBuilder_ == null) {
        ensureDiffFileChunkIsMutable();
        diffFileChunk_.add(index, builderForValue.build());
        onChanged();
      } else {
        diffFileChunkBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder addAllDiffFileChunk(
        java.lang.Iterable<? extends cn.com.unary.initcopy.grpc.entity.DiffFileChunk> values) {
      if (diffFileChunkBuilder_ == null) {
        ensureDiffFileChunkIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, diffFileChunk_);
        onChanged();
      } else {
        diffFileChunkBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder clearDiffFileChunk() {
      if (diffFileChunkBuilder_ == null) {
        diffFileChunk_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        diffFileChunkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public Builder removeDiffFileChunk(int index) {
      if (diffFileChunkBuilder_ == null) {
        ensureDiffFileChunkIsMutable();
        diffFileChunk_.remove(index);
        onChanged();
      } else {
        diffFileChunkBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder getDiffFileChunkBuilder(
        int index) {
      return getDiffFileChunkFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder getDiffFileChunkOrBuilder(
        int index) {
      if (diffFileChunkBuilder_ == null) {
        return diffFileChunk_.get(index);  } else {
        return diffFileChunkBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder> 
         getDiffFileChunkOrBuilderList() {
      if (diffFileChunkBuilder_ != null) {
        return diffFileChunkBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(diffFileChunk_);
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder addDiffFileChunkBuilder() {
      return getDiffFileChunkFieldBuilder().addBuilder(
          cn.com.unary.initcopy.grpc.entity.DiffFileChunk.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder addDiffFileChunkBuilder(
        int index) {
      return getDiffFileChunkFieldBuilder().addBuilder(
          index, cn.com.unary.initcopy.grpc.entity.DiffFileChunk.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileChunk diffFileChunk = 2;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder> 
         getDiffFileChunkBuilderList() {
      return getDiffFileChunkFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.DiffFileChunk, cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder, cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder> 
        getDiffFileChunkFieldBuilder() {
      if (diffFileChunkBuilder_ == null) {
        diffFileChunkBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.com.unary.initcopy.grpc.entity.DiffFileChunk, cn.com.unary.initcopy.grpc.entity.DiffFileChunk.Builder, cn.com.unary.initcopy.grpc.entity.DiffFileChunkOrBuilder>(
                diffFileChunk_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        diffFileChunk_ = null;
      }
      return diffFileChunkBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.com.unary.initcopy.grpc.entity.DiffFileInfo)
  }

  // @@protoc_insertion_point(class_scope:cn.com.unary.initcopy.grpc.entity.DiffFileInfo)
  private static final cn.com.unary.initcopy.grpc.entity.DiffFileInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.unary.initcopy.grpc.entity.DiffFileInfo();
  }

  public static cn.com.unary.initcopy.grpc.entity.DiffFileInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DiffFileInfo>
      PARSER = new com.google.protobuf.AbstractParser<DiffFileInfo>() {
    public DiffFileInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DiffFileInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DiffFileInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DiffFileInfo> getParserForType() {
    return PARSER;
  }

  public cn.com.unary.initcopy.grpc.entity.DiffFileInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

