// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface ExecResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.ExecResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务装态是否正常
   * </pre>
   *
   * <code>optional bool isHealthy = 1;</code>
   */
  boolean getIsHealthy();

  /**
   * <pre>
   * 执行状况代码
   * </pre>
   *
   * <code>optional int32 code = 2;</code>
   */
  int getCode();

  /**
   * <pre>
   * 信息
   * </pre>
   *
   * <code>optional string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <pre>
   * 信息
   * </pre>
   *
   * <code>optional string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
