// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface FileBaseInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.FileBaseInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 校验码
   * </pre>
   *
   * <code>optional string checkSum = 1;</code>
   */
  java.lang.String getCheckSum();
  /**
   * <pre>
   * 校验码
   * </pre>
   *
   * <code>optional string checkSum = 1;</code>
   */
  com.google.protobuf.ByteString
      getCheckSumBytes();

  /**
   * <pre>
   * 修改时间
   * </pre>
   *
   * <code>optional sint64 modifyTime = 2;</code>
   */
  long getModifyTime();

  /**
   * <pre>
   * 文件大小
   * </pre>
   *
   * <code>optional sint64 fileSize = 3;</code>
   */
  long getFileSize();

  /**
   * <pre>
   * 文件全路径名
   * </pre>
   *
   * <code>optional string fullName = 4;</code>
   */
  java.lang.String getFullName();
  /**
   * <pre>
   * 文件全路径名
   * </pre>
   *
   * <code>optional string fullName = 4;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();
}
