// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface ModifyTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.ModifyTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *对应的任务id
   * </pre>
   *
   * <code>optional int32 taskId = 1;</code>
   */
  int getTaskId();

  /**
   * <code>optional .cn.com.unary.initcopy.grpc.constant.ModifyType modifyType = 2;</code>
   */
  int getModifyTypeValue();
  /**
   * <code>optional .cn.com.unary.initcopy.grpc.constant.ModifyType modifyType = 2;</code>
   */
  cn.com.unary.initcopy.grpc.constant.ModifyType getModifyType();

  /**
   * <pre>
   *限速 以M为单位  0为不限速
   * </pre>
   *
   * <code>optional int32 speedLimit = 3;</code>
   */
  int getSpeedLimit();
}
