// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface ProgressInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.ProgressInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *阶段
   * </pre>
   *
   * <code>optional int32 stage = 1;</code>
   */
  int getStage();

  /**
   * <pre>
   *进度百分比   0到100之间的数值
   * </pre>
   *
   * <code>optional int32 progress = 2;</code>
   */
  int getProgress();

  /**
   * <pre>
   *需要同步的文件总数
   * </pre>
   *
   * <code>optional sint64 totalFileNum = 3;</code>
   */
  long getTotalFileNum();

  /**
   * <pre>
   *需要同步的文件总大小 以字节为单位
   * </pre>
   *
   * <code>optional sint64 totalFileSize = 4;</code>
   */
  long getTotalFileSize();

  /**
   * <pre>
   *已经同步的文件总数
   * </pre>
   *
   * <code>optional sint64 syncedFileNum = 5;</code>
   */
  long getSyncedFileNum();

  /**
   * <pre>
   *已经同步的文件总大小
   * </pre>
   *
   * <code>optional sint64 syncedFileSize = 6;</code>
   */
  long getSyncedFileSize();

  /**
   * <pre>
   *当前正在同步的文件
   * </pre>
   *
   * <code>optional string syncingFileName = 7;</code>
   */
  java.lang.String getSyncingFileName();
  /**
   * <pre>
   *当前正在同步的文件
   * </pre>
   *
   * <code>optional string syncingFileName = 7;</code>
   */
  com.google.protobuf.ByteString
      getSyncingFileNameBytes();
}
