// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

/**
 * <pre>
 *进度信息
 * </pre>
 *
 * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ProgressInfo}
 */
public  final class ProgressInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.unary.initcopy.grpc.entity.ProgressInfo)
    ProgressInfoOrBuilder {
  // Use ProgressInfo.newBuilder() to construct.
  private ProgressInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProgressInfo() {
    progress_ = 0;
    totalFileNum_ = 0L;
    totalFileSize_ = "";
    syncedFileNum_ = 0L;
    syncedFileSize_ = "";
    syncingFileName_ = "";
  }

    public static final int PROGRESS_FIELD_NUMBER = 1;
  private ProgressInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            progress_ = input.readInt32();
            break;
          }
          case 16: {

            totalFileNum_ = input.readSInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            totalFileSize_ = s;
            break;
          }
          case 32: {

            syncedFileNum_ = input.readSInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            syncedFileSize_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            syncingFileName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }

    public static final int TOTALFILENUM_FIELD_NUMBER = 2;
    public static final int TOTALFILESIZE_FIELD_NUMBER = 3;
    public static final int SYNCEDFILENUM_FIELD_NUMBER = 4;
    public static final int SYNCEDFILESIZE_FIELD_NUMBER = 5;
  /**
   * <pre>
   *进度百分比   0到100之间的数值
   * </pre>
   *
   * <code>optional int32 progress = 1;</code>
   */
  public int getProgress() {
    return progress_;
  }

    public static final int SYNCINGFILENAME_FIELD_NUMBER = 6;
    private int progress_;
  /**
   * <pre>
   *需要同步的文件总数
   * </pre>
   *
   * <code>optional sint64 totalFileNum = 2;</code>
   */
  public long getTotalFileNum() {
    return totalFileNum_;
  }

    private long totalFileNum_;
    private volatile java.lang.Object totalFileSize_;
    private long syncedFileNum_;
    private volatile java.lang.Object syncedFileSize_;

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ProgressInfo_descriptor;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    /**
     * <pre>
     * 已经同步的文件总数
     * </pre>
     *
     * <code>optional sint64 syncedFileNum = 4;</code>
     */
    public long getSyncedFileNum() {
        return syncedFileNum_;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ProgressInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.com.unary.initcopy.grpc.entity.ProgressInfo.class, cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder.class);
    }

  /**
   * <pre>
   *需要同步的文件总大小 以字节为单位
   * </pre>
   *
   * <code>optional string totalFileSize = 3;</code>
   */
  public java.lang.String getTotalFileSize() {
    java.lang.Object ref = totalFileSize_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totalFileSize_ = s;
      return s;
    }
  }

  /**
   * <pre>
   *需要同步的文件总大小 以字节为单位
   * </pre>
   *
   * <code>optional string totalFileSize = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTotalFileSizeBytes() {
    java.lang.Object ref = totalFileSize_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totalFileSize_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <pre>
   *已经同步的文件总大小
   * </pre>
   *
   * <code>optional string syncedFileSize = 5;</code>
   */
  public java.lang.String getSyncedFileSize() {
    java.lang.Object ref = syncedFileSize_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      syncedFileSize_ = s;
      return s;
    }
  }

  /**
   * <pre>
   *已经同步的文件总大小
   * </pre>
   *
   * <code>optional string syncedFileSize = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSyncedFileSizeBytes() {
    java.lang.Object ref = syncedFileSize_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      syncedFileSize_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  private volatile java.lang.Object syncingFileName_;
  /**
   * <pre>
   *当前正在同步的文件
   * </pre>
   *
   * <code>optional string syncingFileName = 6;</code>
   */
  public java.lang.String getSyncingFileName() {
    java.lang.Object ref = syncingFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      syncingFileName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *当前正在同步的文件
   * </pre>
   *
   * <code>optional string syncingFileName = 6;</code>
   */
  public com.google.protobuf.ByteString
      getSyncingFileNameBytes() {
    java.lang.Object ref = syncingFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      syncingFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (progress_ != 0) {
      output.writeInt32(1, progress_);
    }
    if (totalFileNum_ != 0L) {
      output.writeSInt64(2, totalFileNum_);
    }
    if (!getTotalFileSizeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, totalFileSize_);
    }
    if (syncedFileNum_ != 0L) {
      output.writeSInt64(4, syncedFileNum_);
    }
    if (!getSyncedFileSizeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, syncedFileSize_);
    }
    if (!getSyncingFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, syncingFileName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (progress_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, progress_);
    }
    if (totalFileNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(2, totalFileNum_);
    }
    if (!getTotalFileSizeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, totalFileSize_);
    }
    if (syncedFileNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(4, syncedFileNum_);
    }
    if (!getSyncedFileSizeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, syncedFileSize_);
    }
    if (!getSyncingFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, syncingFileName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.unary.initcopy.grpc.entity.ProgressInfo)) {
      return super.equals(obj);
    }
    cn.com.unary.initcopy.grpc.entity.ProgressInfo other = (cn.com.unary.initcopy.grpc.entity.ProgressInfo) obj;

    boolean result = true;
    result = result && (getProgress()
        == other.getProgress());
    result = result && (getTotalFileNum()
        == other.getTotalFileNum());
    result = result && getTotalFileSize()
        .equals(other.getTotalFileSize());
    result = result && (getSyncedFileNum()
        == other.getSyncedFileNum());
    result = result && getSyncedFileSize()
        .equals(other.getSyncedFileSize());
    result = result && getSyncingFileName()
        .equals(other.getSyncingFileName());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
    hash = (53 * hash) + getProgress();
    hash = (37 * hash) + TOTALFILENUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalFileNum());
    hash = (37 * hash) + TOTALFILESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getTotalFileSize().hashCode();
    hash = (37 * hash) + SYNCEDFILENUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSyncedFileNum());
    hash = (37 * hash) + SYNCEDFILESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSyncedFileSize().hashCode();
    hash = (37 * hash) + SYNCINGFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getSyncingFileName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.unary.initcopy.grpc.entity.ProgressInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   *进度信息
   * </pre>
   *
   * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ProgressInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.unary.initcopy.grpc.entity.ProgressInfo)
      cn.com.unary.initcopy.grpc.entity.ProgressInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ProgressInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ProgressInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.unary.initcopy.grpc.entity.ProgressInfo.class, cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder.class);
    }

    // Construct using cn.com.unary.initcopy.grpc.entity.ProgressInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

      private int progress_ ;

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ProgressInfo_descriptor;
    }

    public cn.com.unary.initcopy.grpc.entity.ProgressInfo getDefaultInstanceForType() {
      return cn.com.unary.initcopy.grpc.entity.ProgressInfo.getDefaultInstance();
    }

    public cn.com.unary.initcopy.grpc.entity.ProgressInfo build() {
      cn.com.unary.initcopy.grpc.entity.ProgressInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.com.unary.initcopy.grpc.entity.ProgressInfo buildPartial() {
      cn.com.unary.initcopy.grpc.entity.ProgressInfo result = new cn.com.unary.initcopy.grpc.entity.ProgressInfo(this);
      result.progress_ = progress_;
      result.totalFileNum_ = totalFileNum_;
      result.totalFileSize_ = totalFileSize_;
      result.syncedFileNum_ = syncedFileNum_;
      result.syncedFileSize_ = syncedFileSize_;
      result.syncingFileName_ = syncingFileName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.unary.initcopy.grpc.entity.ProgressInfo) {
        return mergeFrom((cn.com.unary.initcopy.grpc.entity.ProgressInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.unary.initcopy.grpc.entity.ProgressInfo other) {
      if (other == cn.com.unary.initcopy.grpc.entity.ProgressInfo.getDefaultInstance()) return this;
      if (other.getProgress() != 0) {
        setProgress(other.getProgress());
      }
      if (other.getTotalFileNum() != 0L) {
        setTotalFileNum(other.getTotalFileNum());
      }
      if (!other.getTotalFileSize().isEmpty()) {
        totalFileSize_ = other.totalFileSize_;
        onChanged();
      }
      if (other.getSyncedFileNum() != 0L) {
        setSyncedFileNum(other.getSyncedFileNum());
      }
      if (!other.getSyncedFileSize().isEmpty()) {
        syncedFileSize_ = other.syncedFileSize_;
        onChanged();
      }
      if (!other.getSyncingFileName().isEmpty()) {
        syncingFileName_ = other.syncingFileName_;
        onChanged();
      }
      onChanged();
      return this;
    }

      private long totalFileNum_;
      private java.lang.Object totalFileSize_ = "";

      public Builder clear() {
          super.clear();
          progress_ = 0;

          totalFileNum_ = 0L;

          totalFileSize_ = "";

          syncedFileNum_ = 0L;

          syncedFileSize_ = "";

          syncingFileName_ = "";

          return this;
    }
    /**
     * <pre>
     *进度百分比   0到100之间的数值
     * </pre>
     *
     * <code>optional int32 progress = 1;</code>
     */
    public int getProgress() {
      return progress_;
    }

      public final boolean isInitialized() {
          return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
          cn.com.unary.initcopy.grpc.entity.ProgressInfo parsedMessage = null;
          try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (cn.com.unary.initcopy.grpc.entity.ProgressInfo) e.getUnfinishedMessage();
              throw e.unwrapIOException();
          } finally {
              if (parsedMessage != null) {
                  mergeFrom(parsedMessage);
              }
          }
          return this;
      }

    /**
     * <pre>
     *进度百分比   0到100之间的数值
     * </pre>
     *
     * <code>optional int32 progress = 1;</code>
     */
    public Builder setProgress(int value) {

      progress_ = value;
      onChanged();
      return this;
    }

      /**
       * <pre>
       * 需要同步的文件总数
       * </pre>
       *
       * <code>optional sint64 totalFileNum = 2;</code>
       */
      public long getTotalFileNum() {
          return totalFileNum_;
    }

    /**
     * <pre>
     *进度百分比   0到100之间的数值
     * </pre>
     *
     * <code>optional int32 progress = 1;</code>
     */
    public Builder clearProgress() {

      progress_ = 0;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *需要同步的文件总数
     * </pre>
     *
     * <code>optional sint64 totalFileNum = 2;</code>
     */
    public Builder setTotalFileNum(long value) {

      totalFileNum_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     *需要同步的文件总数
     * </pre>
     *
     * <code>optional sint64 totalFileNum = 2;</code>
     */
    public Builder clearTotalFileNum() {

      totalFileNum_ = 0L;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *需要同步的文件总大小 以字节为单位
     * </pre>
     *
     * <code>optional string totalFileSize = 3;</code>
     */
    public java.lang.String getTotalFileSize() {
      java.lang.Object ref = totalFileSize_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totalFileSize_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <pre>
     *需要同步的文件总大小 以字节为单位
     * </pre>
     *
     * <code>optional string totalFileSize = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTotalFileSizeBytes() {
      java.lang.Object ref = totalFileSize_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalFileSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     *需要同步的文件总大小 以字节为单位
     * </pre>
     *
     * <code>optional string totalFileSize = 3;</code>
     */
    public Builder setTotalFileSizeBytes(
            com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        totalFileSize_ = value;
        onChanged();
        return this;
    }

      /**
       * <pre>
       * 需要同步的文件总大小 以字节为单位
       * </pre>
       *
       * <code>optional string totalFileSize = 3;</code>
       */
      public Builder setTotalFileSize(
              java.lang.String value) {
          if (value == null) {
              throw new NullPointerException();
          }

          totalFileSize_ = value;
          onChanged();
          return this;
      }

    /**
     * <pre>
     *需要同步的文件总大小 以字节为单位
     * </pre>
     *
     * <code>optional string totalFileSize = 3;</code>
     */
    public Builder clearTotalFileSize() {

      totalFileSize_ = getDefaultInstance().getTotalFileSize();
      onChanged();
      return this;
    }

    private long syncedFileNum_ ;
    /**
     * <pre>
     *已经同步的文件总数
     * </pre>
     *
     * <code>optional sint64 syncedFileNum = 4;</code>
     */
    public long getSyncedFileNum() {
      return syncedFileNum_;
    }
    /**
     * <pre>
     *已经同步的文件总数
     * </pre>
     *
     * <code>optional sint64 syncedFileNum = 4;</code>
     */
    public Builder setSyncedFileNum(long value) {
      
      syncedFileNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *已经同步的文件总数
     * </pre>
     *
     * <code>optional sint64 syncedFileNum = 4;</code>
     */
    public Builder clearSyncedFileNum() {
      
      syncedFileNum_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object syncedFileSize_ = "";
    /**
     * <pre>
     *已经同步的文件总大小
     * </pre>
     *
     * <code>optional string syncedFileSize = 5;</code>
     */
    public java.lang.String getSyncedFileSize() {
      java.lang.Object ref = syncedFileSize_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        syncedFileSize_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <pre>
     *已经同步的文件总大小
     * </pre>
     *
     * <code>optional string syncedFileSize = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSyncedFileSizeBytes() {
      java.lang.Object ref = syncedFileSize_;
        if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        syncedFileSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     *已经同步的文件总大小
     * </pre>
     *
     * <code>optional string syncedFileSize = 5;</code>
     */
    public Builder setSyncedFileSizeBytes(
            com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        syncedFileSize_ = value;
        onChanged();
        return this;
    }

      /**
       * <pre>
       * 已经同步的文件总大小
       * </pre>
       *
       * <code>optional string syncedFileSize = 5;</code>
       */
      public Builder setSyncedFileSize(
              java.lang.String value) {
          if (value == null) {
              throw new NullPointerException();
          }

          syncedFileSize_ = value;
          onChanged();
          return this;
      }

    /**
     * <pre>
     *已经同步的文件总大小
     * </pre>
     *
     * <code>optional string syncedFileSize = 5;</code>
     */
    public Builder clearSyncedFileSize() {

      syncedFileSize_ = getDefaultInstance().getSyncedFileSize();
      onChanged();
      return this;
    }

    private java.lang.Object syncingFileName_ = "";
    /**
     * <pre>
     *当前正在同步的文件
     * </pre>
     *
     * <code>optional string syncingFileName = 6;</code>
     */
    public java.lang.String getSyncingFileName() {
      java.lang.Object ref = syncingFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        syncingFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <pre>
     *当前正在同步的文件
     * </pre>
     *
     * <code>optional string syncingFileName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSyncingFileNameBytes() {
        java.lang.Object ref = syncingFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        syncingFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     *当前正在同步的文件
     * </pre>
     *
     * <code>optional string syncingFileName = 6;</code>
     */
    public Builder setSyncingFileNameBytes(
            com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        syncingFileName_ = value;
        onChanged();
        return this;
    }

      /**
       * <pre>
       * 当前正在同步的文件
       * </pre>
       *
       * <code>optional string syncingFileName = 6;</code>
       */
      public Builder setSyncingFileName(
              java.lang.String value) {
          if (value == null) {
              throw new NullPointerException();
          }

          syncingFileName_ = value;
          onChanged();
          return this;
      }

    /**
     * <pre>
     *当前正在同步的文件
     * </pre>
     *
     * <code>optional string syncingFileName = 6;</code>
     */
    public Builder clearSyncingFileName() {

      syncingFileName_ = getDefaultInstance().getSyncingFileName();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.com.unary.initcopy.grpc.entity.ProgressInfo)
  }

  // @@protoc_insertion_point(class_scope:cn.com.unary.initcopy.grpc.entity.ProgressInfo)
  private static final cn.com.unary.initcopy.grpc.entity.ProgressInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.unary.initcopy.grpc.entity.ProgressInfo();
  }

  public static cn.com.unary.initcopy.grpc.entity.ProgressInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProgressInfo>
      PARSER = new com.google.protobuf.AbstractParser<ProgressInfo>() {
    public ProgressInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProgressInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProgressInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProgressInfo> getParserForType() {
    return PARSER;
  }

  public cn.com.unary.initcopy.grpc.entity.ProgressInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

