// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface QueryTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.QueryTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string taskId = 1;</code>
   */
  java.lang.String getTaskId();
  /**
   * <code>optional string taskId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();
}
