// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

/**
 * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ServerInitResp}
 */
public  final class ServerInitResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.unary.initcopy.grpc.entity.ServerInitResp)
    ServerInitRespOrBuilder {
  // Use ServerInitResp.newBuilder() to construct.
  private ServerInitResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerInitResp() {
    taskId_ = 0;
    ready_ = false;
    msg_ = "";
    diffFileInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ServerInitResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            taskId_ = input.readInt32();
            break;
          }
          case 16: {

            ready_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              diffFileInfo_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.DiffFileInfo>();
              mutable_bitField0_ |= 0x00000008;
            }
            diffFileInfo_.add(
                input.readMessage(cn.com.unary.initcopy.grpc.entity.DiffFileInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        diffFileInfo_ = java.util.Collections.unmodifiableList(diffFileInfo_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ServerInitResp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ServerInitResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.com.unary.initcopy.grpc.entity.ServerInitResp.class, cn.com.unary.initcopy.grpc.entity.ServerInitResp.Builder.class);
  }

  private int bitField0_;
  public static final int TASKID_FIELD_NUMBER = 1;
  private int taskId_;
  /**
   * <code>optional int32 taskId = 1;</code>
   */
  public int getTaskId() {
    return taskId_;
  }

  public static final int READY_FIELD_NUMBER = 2;
  private boolean ready_;
  /**
   * <code>optional bool ready = 2;</code>
   */
  public boolean getReady() {
    return ready_;
  }

  public static final int MSG_FIELD_NUMBER = 3;
  private volatile java.lang.Object msg_;
  /**
   * <code>optional string msg = 3;</code>
   */
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>optional string msg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIFFFILEINFO_FIELD_NUMBER = 4;
  private java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileInfo> diffFileInfo_;
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  public java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileInfo> getDiffFileInfoList() {
    return diffFileInfo_;
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder> 
      getDiffFileInfoOrBuilderList() {
    return diffFileInfo_;
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  public int getDiffFileInfoCount() {
    return diffFileInfo_.size();
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.DiffFileInfo getDiffFileInfo(int index) {
    return diffFileInfo_.get(index);
  }
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder getDiffFileInfoOrBuilder(
      int index) {
    return diffFileInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (taskId_ != 0) {
      output.writeInt32(1, taskId_);
    }
    if (ready_ != false) {
      output.writeBool(2, ready_);
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
    }
    for (int i = 0; i < diffFileInfo_.size(); i++) {
      output.writeMessage(4, diffFileInfo_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (taskId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, taskId_);
    }
    if (ready_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, ready_);
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
    }
    for (int i = 0; i < diffFileInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, diffFileInfo_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.unary.initcopy.grpc.entity.ServerInitResp)) {
      return super.equals(obj);
    }
    cn.com.unary.initcopy.grpc.entity.ServerInitResp other = (cn.com.unary.initcopy.grpc.entity.ServerInitResp) obj;

    boolean result = true;
    result = result && (getTaskId()
        == other.getTaskId());
    result = result && (getReady()
        == other.getReady());
    result = result && getMsg()
        .equals(other.getMsg());
    result = result && getDiffFileInfoList()
        .equals(other.getDiffFileInfoList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId();
    hash = (37 * hash) + READY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReady());
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    if (getDiffFileInfoCount() > 0) {
      hash = (37 * hash) + DIFFFILEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getDiffFileInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.unary.initcopy.grpc.entity.ServerInitResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.ServerInitResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.unary.initcopy.grpc.entity.ServerInitResp)
      cn.com.unary.initcopy.grpc.entity.ServerInitRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ServerInitResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ServerInitResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.unary.initcopy.grpc.entity.ServerInitResp.class, cn.com.unary.initcopy.grpc.entity.ServerInitResp.Builder.class);
    }

    // Construct using cn.com.unary.initcopy.grpc.entity.ServerInitResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDiffFileInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = 0;

      ready_ = false;

      msg_ = "";

      if (diffFileInfoBuilder_ == null) {
        diffFileInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        diffFileInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_ServerInitResp_descriptor;
    }

    public cn.com.unary.initcopy.grpc.entity.ServerInitResp getDefaultInstanceForType() {
      return cn.com.unary.initcopy.grpc.entity.ServerInitResp.getDefaultInstance();
    }

    public cn.com.unary.initcopy.grpc.entity.ServerInitResp build() {
      cn.com.unary.initcopy.grpc.entity.ServerInitResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.com.unary.initcopy.grpc.entity.ServerInitResp buildPartial() {
      cn.com.unary.initcopy.grpc.entity.ServerInitResp result = new cn.com.unary.initcopy.grpc.entity.ServerInitResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.taskId_ = taskId_;
      result.ready_ = ready_;
      result.msg_ = msg_;
      if (diffFileInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          diffFileInfo_ = java.util.Collections.unmodifiableList(diffFileInfo_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.diffFileInfo_ = diffFileInfo_;
      } else {
        result.diffFileInfo_ = diffFileInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.unary.initcopy.grpc.entity.ServerInitResp) {
        return mergeFrom((cn.com.unary.initcopy.grpc.entity.ServerInitResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.unary.initcopy.grpc.entity.ServerInitResp other) {
      if (other == cn.com.unary.initcopy.grpc.entity.ServerInitResp.getDefaultInstance()) return this;
      if (other.getTaskId() != 0) {
        setTaskId(other.getTaskId());
      }
      if (other.getReady() != false) {
        setReady(other.getReady());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      if (diffFileInfoBuilder_ == null) {
        if (!other.diffFileInfo_.isEmpty()) {
          if (diffFileInfo_.isEmpty()) {
            diffFileInfo_ = other.diffFileInfo_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDiffFileInfoIsMutable();
            diffFileInfo_.addAll(other.diffFileInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.diffFileInfo_.isEmpty()) {
          if (diffFileInfoBuilder_.isEmpty()) {
            diffFileInfoBuilder_.dispose();
            diffFileInfoBuilder_ = null;
            diffFileInfo_ = other.diffFileInfo_;
            bitField0_ = (bitField0_ & ~0x00000008);
            diffFileInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDiffFileInfoFieldBuilder() : null;
          } else {
            diffFileInfoBuilder_.addAllMessages(other.diffFileInfo_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.com.unary.initcopy.grpc.entity.ServerInitResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.com.unary.initcopy.grpc.entity.ServerInitResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int taskId_ ;
    /**
     * <code>optional int32 taskId = 1;</code>
     */
    public int getTaskId() {
      return taskId_;
    }
    /**
     * <code>optional int32 taskId = 1;</code>
     */
    public Builder setTaskId(int value) {
      
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 taskId = 1;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = 0;
      onChanged();
      return this;
    }

    private boolean ready_ ;
    /**
     * <code>optional bool ready = 2;</code>
     */
    public boolean getReady() {
      return ready_;
    }
    /**
     * <code>optional bool ready = 2;</code>
     */
    public Builder setReady(boolean value) {
      
      ready_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool ready = 2;</code>
     */
    public Builder clearReady() {
      
      ready_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>optional string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>optional string msg = 3;</code>
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

    private java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileInfo> diffFileInfo_ =
      java.util.Collections.emptyList();
    private void ensureDiffFileInfoIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        diffFileInfo_ = new java.util.ArrayList<cn.com.unary.initcopy.grpc.entity.DiffFileInfo>(diffFileInfo_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.DiffFileInfo, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder, cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder> diffFileInfoBuilder_;

    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileInfo> getDiffFileInfoList() {
      if (diffFileInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(diffFileInfo_);
      } else {
        return diffFileInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public int getDiffFileInfoCount() {
      if (diffFileInfoBuilder_ == null) {
        return diffFileInfo_.size();
      } else {
        return diffFileInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileInfo getDiffFileInfo(int index) {
      if (diffFileInfoBuilder_ == null) {
        return diffFileInfo_.get(index);
      } else {
        return diffFileInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder setDiffFileInfo(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileInfo value) {
      if (diffFileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffFileInfoIsMutable();
        diffFileInfo_.set(index, value);
        onChanged();
      } else {
        diffFileInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder setDiffFileInfo(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder builderForValue) {
      if (diffFileInfoBuilder_ == null) {
        ensureDiffFileInfoIsMutable();
        diffFileInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        diffFileInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder addDiffFileInfo(cn.com.unary.initcopy.grpc.entity.DiffFileInfo value) {
      if (diffFileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffFileInfoIsMutable();
        diffFileInfo_.add(value);
        onChanged();
      } else {
        diffFileInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder addDiffFileInfo(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileInfo value) {
      if (diffFileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDiffFileInfoIsMutable();
        diffFileInfo_.add(index, value);
        onChanged();
      } else {
        diffFileInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder addDiffFileInfo(
        cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder builderForValue) {
      if (diffFileInfoBuilder_ == null) {
        ensureDiffFileInfoIsMutable();
        diffFileInfo_.add(builderForValue.build());
        onChanged();
      } else {
        diffFileInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder addDiffFileInfo(
        int index, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder builderForValue) {
      if (diffFileInfoBuilder_ == null) {
        ensureDiffFileInfoIsMutable();
        diffFileInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        diffFileInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder addAllDiffFileInfo(
        java.lang.Iterable<? extends cn.com.unary.initcopy.grpc.entity.DiffFileInfo> values) {
      if (diffFileInfoBuilder_ == null) {
        ensureDiffFileInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, diffFileInfo_);
        onChanged();
      } else {
        diffFileInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder clearDiffFileInfo() {
      if (diffFileInfoBuilder_ == null) {
        diffFileInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        diffFileInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public Builder removeDiffFileInfo(int index) {
      if (diffFileInfoBuilder_ == null) {
        ensureDiffFileInfoIsMutable();
        diffFileInfo_.remove(index);
        onChanged();
      } else {
        diffFileInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder getDiffFileInfoBuilder(
        int index) {
      return getDiffFileInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder getDiffFileInfoOrBuilder(
        int index) {
      if (diffFileInfoBuilder_ == null) {
        return diffFileInfo_.get(index);  } else {
        return diffFileInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public java.util.List<? extends cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder> 
         getDiffFileInfoOrBuilderList() {
      if (diffFileInfoBuilder_ != null) {
        return diffFileInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(diffFileInfo_);
      }
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder addDiffFileInfoBuilder() {
      return getDiffFileInfoFieldBuilder().addBuilder(
          cn.com.unary.initcopy.grpc.entity.DiffFileInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder addDiffFileInfoBuilder(
        int index) {
      return getDiffFileInfoFieldBuilder().addBuilder(
          index, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
     */
    public java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder> 
         getDiffFileInfoBuilderList() {
      return getDiffFileInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.DiffFileInfo, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder, cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder> 
        getDiffFileInfoFieldBuilder() {
      if (diffFileInfoBuilder_ == null) {
        diffFileInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.com.unary.initcopy.grpc.entity.DiffFileInfo, cn.com.unary.initcopy.grpc.entity.DiffFileInfo.Builder, cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder>(
                diffFileInfo_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        diffFileInfo_ = null;
      }
      return diffFileInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.com.unary.initcopy.grpc.entity.ServerInitResp)
  }

  // @@protoc_insertion_point(class_scope:cn.com.unary.initcopy.grpc.entity.ServerInitResp)
  private static final cn.com.unary.initcopy.grpc.entity.ServerInitResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.unary.initcopy.grpc.entity.ServerInitResp();
  }

  public static cn.com.unary.initcopy.grpc.entity.ServerInitResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerInitResp>
      PARSER = new com.google.protobuf.AbstractParser<ServerInitResp>() {
    public ServerInitResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerInitResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerInitResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerInitResp> getParserForType() {
    return PARSER;
  }

  public cn.com.unary.initcopy.grpc.entity.ServerInitResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

