// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface ServerInitRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.ServerInitResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 taskId = 1;</code>
   */
  int getTaskId();

  /**
   * <code>optional bool ready = 2;</code>
   */
  boolean getReady();

  /**
   * <code>optional string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileInfo> 
      getDiffFileInfoList();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  cn.com.unary.initcopy.grpc.entity.DiffFileInfo getDiffFileInfo(int index);
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  int getDiffFileInfoCount();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  java.util.List<? extends cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder> 
      getDiffFileInfoOrBuilderList();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfo = 4;</code>
   */
  cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder getDiffFileInfoOrBuilder(
      int index);
}
