// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_control_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface ServerInitRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.ServerInitResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string taskId = 1;</code>
   */
  java.lang.String getTaskId();

  /**
   * <code>optional string taskId = 1;</code>
   */
  com.google.protobuf.ByteString
  getTaskIdBytes();

  /**
   * <code>optional bool ready = 2;</code>
   */
  boolean getReady();

  /**
   * <code>optional string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfos = 4;</code>
   */
  java.util.List<cn.com.unary.initcopy.grpc.entity.DiffFileInfo> 
      getDiffFileInfosList();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfos = 4;</code>
   */
  cn.com.unary.initcopy.grpc.entity.DiffFileInfo getDiffFileInfos(int index);
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfos = 4;</code>
   */
  int getDiffFileInfosCount();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfos = 4;</code>
   */
  java.util.List<? extends cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder> 
      getDiffFileInfosOrBuilderList();
  /**
   * <code>repeated .cn.com.unary.initcopy.grpc.entity.DiffFileInfo diffFileInfos = 4;</code>
   */
  cn.com.unary.initcopy.grpc.entity.DiffFileInfoOrBuilder getDiffFileInfosOrBuilder(
      int index);
}
