// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface SyncTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.SyncTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *目标端IP
   * </pre>
   *
   * <code>optional string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <pre>
   *目标端IP
   * </pre>
   *
   * <code>optional string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   *目标端端口号
   * </pre>
   *
   * <code>optional int32 port = 2;</code>
   */
  int getPort();
}
