// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

/**
 * <pre>
 *同步任务
 * </pre>
 *
 * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.SyncTask}
 */
public  final class SyncTask extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.unary.initcopy.grpc.entity.SyncTask)
    SyncTaskOrBuilder {
  // Use SyncTask.newBuilder() to construct.
  private SyncTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncTask() {
    taskId_ = "";
    syncType_ = 0;
    compressType_ = 0;
    encryptType_ = 0;
    packType_ = 0;
    speedLimit_ = 0;
    targetDir_ = "";
    file_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SyncTask(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 18: {
            cn.com.unary.initcopy.grpc.entity.SyncTarget.Builder subBuilder = null;
            if (targetInfo_ != null) {
              subBuilder = targetInfo_.toBuilder();
            }
            targetInfo_ = input.readMessage(cn.com.unary.initcopy.grpc.entity.SyncTarget.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(targetInfo_);
              targetInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            syncType_ = rawValue;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            compressType_ = rawValue;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            encryptType_ = rawValue;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            packType_ = rawValue;
            break;
          }
          case 56: {

            speedLimit_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            targetDir_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              file_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000100;
            }
            file_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        file_ = file_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_SyncTask_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_SyncTask_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.com.unary.initcopy.grpc.entity.SyncTask.class, cn.com.unary.initcopy.grpc.entity.SyncTask.Builder.class);
  }

  private int bitField0_;
  public static final int TASKID_FIELD_NUMBER = 1;
  private volatile java.lang.Object taskId_;
  /**
   * <pre>
   *任务ID
   * </pre>
   *
   * <code>optional string taskId = 1;</code>
   */
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *任务ID
   * </pre>
   *
   * <code>optional string taskId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGETINFO_FIELD_NUMBER = 2;
  private cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo_;
  /**
   * <pre>
   * 目标端IP及端口信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
   */
  public boolean hasTargetInfo() {
    return targetInfo_ != null;
  }
  /**
   * <pre>
   * 目标端IP及端口信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.SyncTarget getTargetInfo() {
    return targetInfo_ == null ? cn.com.unary.initcopy.grpc.entity.SyncTarget.getDefaultInstance() : targetInfo_;
  }
  /**
   * <pre>
   * 目标端IP及端口信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.SyncTargetOrBuilder getTargetInfoOrBuilder() {
    return getTargetInfo();
  }

  public static final int SYNCTYPE_FIELD_NUMBER = 3;
  private int syncType_;
  /**
   * <pre>
   *同步方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 3;</code>
   */
  public int getSyncTypeValue() {
    return syncType_;
  }
  /**
   * <pre>
   *同步方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 3;</code>
   */
  public cn.com.unary.initcopy.grpc.constant.SyncType getSyncType() {
    cn.com.unary.initcopy.grpc.constant.SyncType result = cn.com.unary.initcopy.grpc.constant.SyncType.valueOf(syncType_);
    return result == null ? cn.com.unary.initcopy.grpc.constant.SyncType.UNRECOGNIZED : result;
  }

  public static final int COMPRESSTYPE_FIELD_NUMBER = 4;
  private int compressType_;
  /**
   * <pre>
   *压缩方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.CompressType compressType = 4;</code>
   */
  public int getCompressTypeValue() {
    return compressType_;
  }
  /**
   * <pre>
   *压缩方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.CompressType compressType = 4;</code>
   */
  public cn.com.unary.initcopy.grpc.constant.CompressType getCompressType() {
    cn.com.unary.initcopy.grpc.constant.CompressType result = cn.com.unary.initcopy.grpc.constant.CompressType.valueOf(compressType_);
    return result == null ? cn.com.unary.initcopy.grpc.constant.CompressType.UNRECOGNIZED : result;
  }

  public static final int ENCRYPTTYPE_FIELD_NUMBER = 5;
  private int encryptType_;
  /**
   * <pre>
   *加密方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.EncryptType encryptType = 5;</code>
   */
  public int getEncryptTypeValue() {
    return encryptType_;
  }
  /**
   * <pre>
   *加密方式
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.EncryptType encryptType = 5;</code>
   */
  public cn.com.unary.initcopy.grpc.constant.EncryptType getEncryptType() {
    cn.com.unary.initcopy.grpc.constant.EncryptType result = cn.com.unary.initcopy.grpc.constant.EncryptType.valueOf(encryptType_);
    return result == null ? cn.com.unary.initcopy.grpc.constant.EncryptType.UNRECOGNIZED : result;
  }

  public static final int PACKTYPE_FIELD_NUMBER = 6;
  private int packType_;
  /**
   * <pre>
   *打包类型
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.PackType packType = 6;</code>
   */
  public int getPackTypeValue() {
    return packType_;
  }
  /**
   * <pre>
   *打包类型
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.constant.PackType packType = 6;</code>
   */
  public cn.com.unary.initcopy.grpc.constant.PackType getPackType() {
    cn.com.unary.initcopy.grpc.constant.PackType result = cn.com.unary.initcopy.grpc.constant.PackType.valueOf(packType_);
    return result == null ? cn.com.unary.initcopy.grpc.constant.PackType.UNRECOGNIZED : result;
  }

  public static final int SPEEDLIMIT_FIELD_NUMBER = 7;
  private int speedLimit_;
  /**
   * <pre>
   *限速 以M为单位  0为不限速
   * </pre>
   *
   * <code>optional int32 speedLimit = 7;</code>
   */
  public int getSpeedLimit() {
    return speedLimit_;
  }

  public static final int TARGETDIR_FIELD_NUMBER = 8;
  private volatile java.lang.Object targetDir_;
  /**
   * <pre>
   *要同步的目标目录
   * </pre>
   *
   * <code>optional string TargetDir = 8;</code>
   */
  public java.lang.String getTargetDir() {
    java.lang.Object ref = targetDir_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetDir_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *要同步的目标目录
   * </pre>
   *
   * <code>optional string TargetDir = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTargetDirBytes() {
    java.lang.Object ref = targetDir_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList file_;
  /**
   * <pre>
   *要同步的源文件
   * </pre>
   *
   * <code>repeated string file = 9;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFileList() {
    return file_;
  }
  /**
   * <pre>
   *要同步的源文件
   * </pre>
   *
   * <code>repeated string file = 9;</code>
   */
  public int getFileCount() {
    return file_.size();
  }
  /**
   * <pre>
   *要同步的源文件
   * </pre>
   *
   * <code>repeated string file = 9;</code>
   */
  public java.lang.String getFile(int index) {
    return file_.get(index);
  }
  /**
   * <pre>
   *要同步的源文件
   * </pre>
   *
   * <code>repeated string file = 9;</code>
   */
  public com.google.protobuf.ByteString
      getFileBytes(int index) {
    return file_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
    }
    if (targetInfo_ != null) {
      output.writeMessage(2, getTargetInfo());
    }
    if (syncType_ != cn.com.unary.initcopy.grpc.constant.SyncType.SYNC_ALL.getNumber()) {
      output.writeEnum(3, syncType_);
    }
    if (compressType_ != cn.com.unary.initcopy.grpc.constant.CompressType.COMPRESS_NONE.getNumber()) {
      output.writeEnum(4, compressType_);
    }
    if (encryptType_ != cn.com.unary.initcopy.grpc.constant.EncryptType.ENCRYPT_NONE.getNumber()) {
      output.writeEnum(5, encryptType_);
    }
    if (packType_ != cn.com.unary.initcopy.grpc.constant.PackType.PACK_NONE.getNumber()) {
      output.writeEnum(6, packType_);
    }
    if (speedLimit_ != 0) {
      output.writeInt32(7, speedLimit_);
    }
    if (!getTargetDirBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, targetDir_);
    }
    for (int i = 0; i < file_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, file_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
    }
    if (targetInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTargetInfo());
    }
    if (syncType_ != cn.com.unary.initcopy.grpc.constant.SyncType.SYNC_ALL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, syncType_);
    }
    if (compressType_ != cn.com.unary.initcopy.grpc.constant.CompressType.COMPRESS_NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, compressType_);
    }
    if (encryptType_ != cn.com.unary.initcopy.grpc.constant.EncryptType.ENCRYPT_NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, encryptType_);
    }
    if (packType_ != cn.com.unary.initcopy.grpc.constant.PackType.PACK_NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, packType_);
    }
    if (speedLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, speedLimit_);
    }
    if (!getTargetDirBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, targetDir_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < file_.size(); i++) {
        dataSize += computeStringSizeNoTag(file_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFileList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.unary.initcopy.grpc.entity.SyncTask)) {
      return super.equals(obj);
    }
    cn.com.unary.initcopy.grpc.entity.SyncTask other = (cn.com.unary.initcopy.grpc.entity.SyncTask) obj;

    boolean result = true;
    result = result && getTaskId()
        .equals(other.getTaskId());
    result = result && (hasTargetInfo() == other.hasTargetInfo());
    if (hasTargetInfo()) {
      result = result && getTargetInfo()
          .equals(other.getTargetInfo());
    }
    result = result && syncType_ == other.syncType_;
    result = result && compressType_ == other.compressType_;
    result = result && encryptType_ == other.encryptType_;
    result = result && packType_ == other.packType_;
    result = result && (getSpeedLimit()
        == other.getSpeedLimit());
    result = result && getTargetDir()
        .equals(other.getTargetDir());
    result = result && getFileList()
        .equals(other.getFileList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    if (hasTargetInfo()) {
      hash = (37 * hash) + TARGETINFO_FIELD_NUMBER;
      hash = (53 * hash) + getTargetInfo().hashCode();
    }
    hash = (37 * hash) + SYNCTYPE_FIELD_NUMBER;
    hash = (53 * hash) + syncType_;
    hash = (37 * hash) + COMPRESSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + compressType_;
    hash = (37 * hash) + ENCRYPTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + encryptType_;
    hash = (37 * hash) + PACKTYPE_FIELD_NUMBER;
    hash = (53 * hash) + packType_;
    hash = (37 * hash) + SPEEDLIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getSpeedLimit();
    hash = (37 * hash) + TARGETDIR_FIELD_NUMBER;
    hash = (53 * hash) + getTargetDir().hashCode();
    if (getFileCount() > 0) {
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFileList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.SyncTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.unary.initcopy.grpc.entity.SyncTask prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *同步任务
   * </pre>
   *
   * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.SyncTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.unary.initcopy.grpc.entity.SyncTask)
      cn.com.unary.initcopy.grpc.entity.SyncTaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_SyncTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_SyncTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.unary.initcopy.grpc.entity.SyncTask.class, cn.com.unary.initcopy.grpc.entity.SyncTask.Builder.class);
    }

    // Construct using cn.com.unary.initcopy.grpc.entity.SyncTask.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = "";

      if (targetInfoBuilder_ == null) {
        targetInfo_ = null;
      } else {
        targetInfo_ = null;
        targetInfoBuilder_ = null;
      }
      syncType_ = 0;

      compressType_ = 0;

      encryptType_ = 0;

      packType_ = 0;

      speedLimit_ = 0;

      targetDir_ = "";

      file_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_SyncTask_descriptor;
    }

    public cn.com.unary.initcopy.grpc.entity.SyncTask getDefaultInstanceForType() {
      return cn.com.unary.initcopy.grpc.entity.SyncTask.getDefaultInstance();
    }

    public cn.com.unary.initcopy.grpc.entity.SyncTask build() {
      cn.com.unary.initcopy.grpc.entity.SyncTask result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.com.unary.initcopy.grpc.entity.SyncTask buildPartial() {
      cn.com.unary.initcopy.grpc.entity.SyncTask result = new cn.com.unary.initcopy.grpc.entity.SyncTask(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.taskId_ = taskId_;
      if (targetInfoBuilder_ == null) {
        result.targetInfo_ = targetInfo_;
      } else {
        result.targetInfo_ = targetInfoBuilder_.build();
      }
      result.syncType_ = syncType_;
      result.compressType_ = compressType_;
      result.encryptType_ = encryptType_;
      result.packType_ = packType_;
      result.speedLimit_ = speedLimit_;
      result.targetDir_ = targetDir_;
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        file_ = file_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.file_ = file_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.unary.initcopy.grpc.entity.SyncTask) {
        return mergeFrom((cn.com.unary.initcopy.grpc.entity.SyncTask)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.unary.initcopy.grpc.entity.SyncTask other) {
      if (other == cn.com.unary.initcopy.grpc.entity.SyncTask.getDefaultInstance()) return this;
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (other.hasTargetInfo()) {
        mergeTargetInfo(other.getTargetInfo());
      }
      if (other.syncType_ != 0) {
        setSyncTypeValue(other.getSyncTypeValue());
      }
      if (other.compressType_ != 0) {
        setCompressTypeValue(other.getCompressTypeValue());
      }
      if (other.encryptType_ != 0) {
        setEncryptTypeValue(other.getEncryptTypeValue());
      }
      if (other.packType_ != 0) {
        setPackTypeValue(other.getPackTypeValue());
      }
      if (other.getSpeedLimit() != 0) {
        setSpeedLimit(other.getSpeedLimit());
      }
      if (!other.getTargetDir().isEmpty()) {
        targetDir_ = other.targetDir_;
        onChanged();
      }
      if (!other.file_.isEmpty()) {
        if (file_.isEmpty()) {
          file_ = other.file_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureFileIsMutable();
          file_.addAll(other.file_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.com.unary.initcopy.grpc.entity.SyncTask parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.com.unary.initcopy.grpc.entity.SyncTask) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object taskId_ = "";
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 1;</code>
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 1;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务ID
     * </pre>
     *
     * <code>optional string taskId = 1;</code>
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }

    private cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.SyncTarget, cn.com.unary.initcopy.grpc.entity.SyncTarget.Builder, cn.com.unary.initcopy.grpc.entity.SyncTargetOrBuilder> targetInfoBuilder_;
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public boolean hasTargetInfo() {
      return targetInfoBuilder_ != null || targetInfo_ != null;
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.SyncTarget getTargetInfo() {
      if (targetInfoBuilder_ == null) {
        return targetInfo_ == null ? cn.com.unary.initcopy.grpc.entity.SyncTarget.getDefaultInstance() : targetInfo_;
      } else {
        return targetInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public Builder setTargetInfo(cn.com.unary.initcopy.grpc.entity.SyncTarget value) {
      if (targetInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        targetInfo_ = value;
        onChanged();
      } else {
        targetInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public Builder setTargetInfo(
        cn.com.unary.initcopy.grpc.entity.SyncTarget.Builder builderForValue) {
      if (targetInfoBuilder_ == null) {
        targetInfo_ = builderForValue.build();
        onChanged();
      } else {
        targetInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public Builder mergeTargetInfo(cn.com.unary.initcopy.grpc.entity.SyncTarget value) {
      if (targetInfoBuilder_ == null) {
        if (targetInfo_ != null) {
          targetInfo_ =
            cn.com.unary.initcopy.grpc.entity.SyncTarget.newBuilder(targetInfo_).mergeFrom(value).buildPartial();
        } else {
          targetInfo_ = value;
        }
        onChanged();
      } else {
        targetInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public Builder clearTargetInfo() {
      if (targetInfoBuilder_ == null) {
        targetInfo_ = null;
        onChanged();
      } else {
        targetInfo_ = null;
        targetInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.SyncTarget.Builder getTargetInfoBuilder() {
      
      onChanged();
      return getTargetInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.SyncTargetOrBuilder getTargetInfoOrBuilder() {
      if (targetInfoBuilder_ != null) {
        return targetInfoBuilder_.getMessageOrBuilder();
      } else {
        return targetInfo_ == null ?
            cn.com.unary.initcopy.grpc.entity.SyncTarget.getDefaultInstance() : targetInfo_;
      }
    }
    /**
     * <pre>
     * 目标端IP及端口信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.SyncTarget targetInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.SyncTarget, cn.com.unary.initcopy.grpc.entity.SyncTarget.Builder, cn.com.unary.initcopy.grpc.entity.SyncTargetOrBuilder> 
        getTargetInfoFieldBuilder() {
      if (targetInfoBuilder_ == null) {
        targetInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.com.unary.initcopy.grpc.entity.SyncTarget, cn.com.unary.initcopy.grpc.entity.SyncTarget.Builder, cn.com.unary.initcopy.grpc.entity.SyncTargetOrBuilder>(
                getTargetInfo(),
                getParentForChildren(),
                isClean());
        targetInfo_ = null;
      }
      return targetInfoBuilder_;
    }

    private int syncType_ = 0;
    /**
     * <pre>
     *同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 3;</code>
     */
    public int getSyncTypeValue() {
      return syncType_;
    }
    /**
     * <pre>
     *同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 3;</code>
     */
    public Builder setSyncTypeValue(int value) {
      syncType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 3;</code>
     */
    public cn.com.unary.initcopy.grpc.constant.SyncType getSyncType() {
      cn.com.unary.initcopy.grpc.constant.SyncType result = cn.com.unary.initcopy.grpc.constant.SyncType.valueOf(syncType_);
      return result == null ? cn.com.unary.initcopy.grpc.constant.SyncType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 3;</code>
     */
    public Builder setSyncType(cn.com.unary.initcopy.grpc.constant.SyncType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      syncType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *同步方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.SyncType syncType = 3;</code>
     */
    public Builder clearSyncType() {
      
      syncType_ = 0;
      onChanged();
      return this;
    }

    private int compressType_ = 0;
    /**
     * <pre>
     *压缩方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.CompressType compressType = 4;</code>
     */
    public int getCompressTypeValue() {
      return compressType_;
    }
    /**
     * <pre>
     *压缩方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.CompressType compressType = 4;</code>
     */
    public Builder setCompressTypeValue(int value) {
      compressType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *压缩方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.CompressType compressType = 4;</code>
     */
    public cn.com.unary.initcopy.grpc.constant.CompressType getCompressType() {
      cn.com.unary.initcopy.grpc.constant.CompressType result = cn.com.unary.initcopy.grpc.constant.CompressType.valueOf(compressType_);
      return result == null ? cn.com.unary.initcopy.grpc.constant.CompressType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *压缩方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.CompressType compressType = 4;</code>
     */
    public Builder setCompressType(cn.com.unary.initcopy.grpc.constant.CompressType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      compressType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *压缩方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.CompressType compressType = 4;</code>
     */
    public Builder clearCompressType() {
      
      compressType_ = 0;
      onChanged();
      return this;
    }

    private int encryptType_ = 0;
    /**
     * <pre>
     *加密方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.EncryptType encryptType = 5;</code>
     */
    public int getEncryptTypeValue() {
      return encryptType_;
    }
    /**
     * <pre>
     *加密方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.EncryptType encryptType = 5;</code>
     */
    public Builder setEncryptTypeValue(int value) {
      encryptType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *加密方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.EncryptType encryptType = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.constant.EncryptType getEncryptType() {
      cn.com.unary.initcopy.grpc.constant.EncryptType result = cn.com.unary.initcopy.grpc.constant.EncryptType.valueOf(encryptType_);
      return result == null ? cn.com.unary.initcopy.grpc.constant.EncryptType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *加密方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.EncryptType encryptType = 5;</code>
     */
    public Builder setEncryptType(cn.com.unary.initcopy.grpc.constant.EncryptType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      encryptType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *加密方式
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.EncryptType encryptType = 5;</code>
     */
    public Builder clearEncryptType() {
      
      encryptType_ = 0;
      onChanged();
      return this;
    }

    private int packType_ = 0;
    /**
     * <pre>
     *打包类型
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.PackType packType = 6;</code>
     */
    public int getPackTypeValue() {
      return packType_;
    }
    /**
     * <pre>
     *打包类型
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.PackType packType = 6;</code>
     */
    public Builder setPackTypeValue(int value) {
      packType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *打包类型
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.PackType packType = 6;</code>
     */
    public cn.com.unary.initcopy.grpc.constant.PackType getPackType() {
      cn.com.unary.initcopy.grpc.constant.PackType result = cn.com.unary.initcopy.grpc.constant.PackType.valueOf(packType_);
      return result == null ? cn.com.unary.initcopy.grpc.constant.PackType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *打包类型
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.PackType packType = 6;</code>
     */
    public Builder setPackType(cn.com.unary.initcopy.grpc.constant.PackType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      packType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *打包类型
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.constant.PackType packType = 6;</code>
     */
    public Builder clearPackType() {
      
      packType_ = 0;
      onChanged();
      return this;
    }

    private int speedLimit_ ;
    /**
     * <pre>
     *限速 以M为单位  0为不限速
     * </pre>
     *
     * <code>optional int32 speedLimit = 7;</code>
     */
    public int getSpeedLimit() {
      return speedLimit_;
    }
    /**
     * <pre>
     *限速 以M为单位  0为不限速
     * </pre>
     *
     * <code>optional int32 speedLimit = 7;</code>
     */
    public Builder setSpeedLimit(int value) {
      
      speedLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *限速 以M为单位  0为不限速
     * </pre>
     *
     * <code>optional int32 speedLimit = 7;</code>
     */
    public Builder clearSpeedLimit() {
      
      speedLimit_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object targetDir_ = "";
    /**
     * <pre>
     *要同步的目标目录
     * </pre>
     *
     * <code>optional string TargetDir = 8;</code>
     */
    public java.lang.String getTargetDir() {
      java.lang.Object ref = targetDir_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetDir_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *要同步的目标目录
     * </pre>
     *
     * <code>optional string TargetDir = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTargetDirBytes() {
      java.lang.Object ref = targetDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *要同步的目标目录
     * </pre>
     *
     * <code>optional string TargetDir = 8;</code>
     */
    public Builder setTargetDir(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetDir_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要同步的目标目录
     * </pre>
     *
     * <code>optional string TargetDir = 8;</code>
     */
    public Builder clearTargetDir() {
      
      targetDir_ = getDefaultInstance().getTargetDir();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要同步的目标目录
     * </pre>
     *
     * <code>optional string TargetDir = 8;</code>
     */
    public Builder setTargetDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetDir_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList file_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFileIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        file_ = new com.google.protobuf.LazyStringArrayList(file_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFileList() {
      return file_.getUnmodifiableView();
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public int getFileCount() {
      return file_.size();
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public java.lang.String getFile(int index) {
      return file_.get(index);
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public com.google.protobuf.ByteString
        getFileBytes(int index) {
      return file_.getByteString(index);
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public Builder setFile(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFileIsMutable();
      file_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public Builder addFile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFileIsMutable();
      file_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public Builder addAllFile(
        java.lang.Iterable<java.lang.String> values) {
      ensureFileIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, file_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public Builder clearFile() {
      file_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *要同步的源文件
     * </pre>
     *
     * <code>repeated string file = 9;</code>
     */
    public Builder addFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFileIsMutable();
      file_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.com.unary.initcopy.grpc.entity.SyncTask)
  }

  // @@protoc_insertion_point(class_scope:cn.com.unary.initcopy.grpc.entity.SyncTask)
  private static final cn.com.unary.initcopy.grpc.entity.SyncTask DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.unary.initcopy.grpc.entity.SyncTask();
  }

  public static cn.com.unary.initcopy.grpc.entity.SyncTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncTask>
      PARSER = new com.google.protobuf.AbstractParser<SyncTask>() {
    public SyncTask parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncTask(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SyncTask> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncTask> getParserForType() {
    return PARSER;
  }

  public cn.com.unary.initcopy.grpc.entity.SyncTask getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

