// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

public interface TaskStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.unary.initcopy.grpc.entity.TaskState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ExecResult execResult = 2;</code>
   */
  boolean hasExecResult();
  /**
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ExecResult execResult = 2;</code>
   */
  cn.com.unary.initcopy.grpc.entity.ExecResult getExecResult();
  /**
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ExecResult execResult = 2;</code>
   */
  cn.com.unary.initcopy.grpc.entity.ExecResultOrBuilder getExecResultOrBuilder();

  /**
   * <pre>
   *进度信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 3;</code>
   */
  boolean hasProgressInfo();
  /**
   * <pre>
   *进度信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 3;</code>
   */
  cn.com.unary.initcopy.grpc.entity.ProgressInfo getProgressInfo();
  /**
   * <pre>
   *进度信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 3;</code>
   */
  cn.com.unary.initcopy.grpc.entity.ProgressInfoOrBuilder getProgressInfoOrBuilder();
}
