// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_entity.proto

package cn.com.unary.initcopy.grpc.entity;

/**
 * <pre>
 * 任务状态
 * </pre>
 *
 * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.TaskState}
 */
public  final class TaskState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.unary.initcopy.grpc.entity.TaskState)
    TaskStateOrBuilder {
  // Use TaskState.newBuilder() to construct.
  private TaskState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskState() {
    success_ = false;
    code_ = 0;
    msg_ = "";
    taskId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TaskState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 16: {

            code_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 42: {
            cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder subBuilder = null;
            if (progressInfo_ != null) {
              subBuilder = progressInfo_.toBuilder();
            }
            progressInfo_ = input.readMessage(cn.com.unary.initcopy.grpc.entity.ProgressInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(progressInfo_);
              progressInfo_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_TaskState_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_TaskState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.com.unary.initcopy.grpc.entity.TaskState.class, cn.com.unary.initcopy.grpc.entity.TaskState.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <pre>
   * 是否成功
   * </pre>
   *
   * <code>optional bool success = 1;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private int code_;
  /**
   * <pre>
   * 代码
   * </pre>
   *
   * <code>optional int32 code = 2;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MSG_FIELD_NUMBER = 3;
  private volatile java.lang.Object msg_;
  /**
   * <pre>
   * 信息
   * </pre>
   *
   * <code>optional string msg = 3;</code>
   */
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 信息
   * </pre>
   *
   * <code>optional string msg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASKID_FIELD_NUMBER = 4;
  private volatile java.lang.Object taskId_;
  /**
   * <pre>
   *对应的任务id
   * </pre>
   *
   * <code>optional string taskId = 4;</code>
   */
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *对应的任务id
   * </pre>
   *
   * <code>optional string taskId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROGRESSINFO_FIELD_NUMBER = 5;
  private cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo_;
  /**
   * <pre>
   *进度信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
   */
  public boolean hasProgressInfo() {
    return progressInfo_ != null;
  }
  /**
   * <pre>
   *进度信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.ProgressInfo getProgressInfo() {
    return progressInfo_ == null ? cn.com.unary.initcopy.grpc.entity.ProgressInfo.getDefaultInstance() : progressInfo_;
  }
  /**
   * <pre>
   *进度信息
   * </pre>
   *
   * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
   */
  public cn.com.unary.initcopy.grpc.entity.ProgressInfoOrBuilder getProgressInfoOrBuilder() {
    return getProgressInfo();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (code_ != 0) {
      output.writeInt32(2, code_);
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, taskId_);
    }
    if (progressInfo_ != null) {
      output.writeMessage(5, getProgressInfo());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, code_);
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, taskId_);
    }
    if (progressInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getProgressInfo());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.unary.initcopy.grpc.entity.TaskState)) {
      return super.equals(obj);
    }
    cn.com.unary.initcopy.grpc.entity.TaskState other = (cn.com.unary.initcopy.grpc.entity.TaskState) obj;

    boolean result = true;
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && (getCode()
        == other.getCode());
    result = result && getMsg()
        .equals(other.getMsg());
    result = result && getTaskId()
        .equals(other.getTaskId());
    result = result && (hasProgressInfo() == other.hasProgressInfo());
    if (hasProgressInfo()) {
      result = result && getProgressInfo()
          .equals(other.getProgressInfo());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    if (hasProgressInfo()) {
      hash = (37 * hash) + PROGRESSINFO_FIELD_NUMBER;
      hash = (53 * hash) + getProgressInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.unary.initcopy.grpc.entity.TaskState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.unary.initcopy.grpc.entity.TaskState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 任务状态
   * </pre>
   *
   * Protobuf type {@code cn.com.unary.initcopy.grpc.entity.TaskState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.unary.initcopy.grpc.entity.TaskState)
      cn.com.unary.initcopy.grpc.entity.TaskStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_TaskState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_TaskState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.unary.initcopy.grpc.entity.TaskState.class, cn.com.unary.initcopy.grpc.entity.TaskState.Builder.class);
    }

    // Construct using cn.com.unary.initcopy.grpc.entity.TaskState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      success_ = false;

      code_ = 0;

      msg_ = "";

      taskId_ = "";

      if (progressInfoBuilder_ == null) {
        progressInfo_ = null;
      } else {
        progressInfo_ = null;
        progressInfoBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.unary.initcopy.grpc.entity.IC_Entity.internal_static_cn_com_unary_initcopy_grpc_entity_TaskState_descriptor;
    }

    public cn.com.unary.initcopy.grpc.entity.TaskState getDefaultInstanceForType() {
      return cn.com.unary.initcopy.grpc.entity.TaskState.getDefaultInstance();
    }

    public cn.com.unary.initcopy.grpc.entity.TaskState build() {
      cn.com.unary.initcopy.grpc.entity.TaskState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.com.unary.initcopy.grpc.entity.TaskState buildPartial() {
      cn.com.unary.initcopy.grpc.entity.TaskState result = new cn.com.unary.initcopy.grpc.entity.TaskState(this);
      result.success_ = success_;
      result.code_ = code_;
      result.msg_ = msg_;
      result.taskId_ = taskId_;
      if (progressInfoBuilder_ == null) {
        result.progressInfo_ = progressInfo_;
      } else {
        result.progressInfo_ = progressInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.unary.initcopy.grpc.entity.TaskState) {
        return mergeFrom((cn.com.unary.initcopy.grpc.entity.TaskState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.unary.initcopy.grpc.entity.TaskState other) {
      if (other == cn.com.unary.initcopy.grpc.entity.TaskState.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (other.hasProgressInfo()) {
        mergeProgressInfo(other.getProgressInfo());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.com.unary.initcopy.grpc.entity.TaskState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.com.unary.initcopy.grpc.entity.TaskState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean success_ ;
    /**
     * <pre>
     * 是否成功
     * </pre>
     *
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <pre>
     * 是否成功
     * </pre>
     *
     * <code>optional bool success = 1;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否成功
     * </pre>
     *
     * <code>optional bool success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private int code_ ;
    /**
     * <pre>
     * 代码
     * </pre>
     *
     * <code>optional int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     * 代码
     * </pre>
     *
     * <code>optional int32 code = 2;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 代码
     * </pre>
     *
     * <code>optional int32 code = 2;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>optional string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>optional string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>optional string msg = 3;</code>
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>optional string msg = 3;</code>
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 信息
     * </pre>
     *
     * <code>optional string msg = 3;</code>
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <pre>
     *对应的任务id
     * </pre>
     *
     * <code>optional string taskId = 4;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *对应的任务id
     * </pre>
     *
     * <code>optional string taskId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *对应的任务id
     * </pre>
     *
     * <code>optional string taskId = 4;</code>
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *对应的任务id
     * </pre>
     *
     * <code>optional string taskId = 4;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *对应的任务id
     * </pre>
     *
     * <code>optional string taskId = 4;</code>
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }

    private cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.ProgressInfo, cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder, cn.com.unary.initcopy.grpc.entity.ProgressInfoOrBuilder> progressInfoBuilder_;
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public boolean hasProgressInfo() {
      return progressInfoBuilder_ != null || progressInfo_ != null;
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.ProgressInfo getProgressInfo() {
      if (progressInfoBuilder_ == null) {
        return progressInfo_ == null ? cn.com.unary.initcopy.grpc.entity.ProgressInfo.getDefaultInstance() : progressInfo_;
      } else {
        return progressInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public Builder setProgressInfo(cn.com.unary.initcopy.grpc.entity.ProgressInfo value) {
      if (progressInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        progressInfo_ = value;
        onChanged();
      } else {
        progressInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public Builder setProgressInfo(
        cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder builderForValue) {
      if (progressInfoBuilder_ == null) {
        progressInfo_ = builderForValue.build();
        onChanged();
      } else {
        progressInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public Builder mergeProgressInfo(cn.com.unary.initcopy.grpc.entity.ProgressInfo value) {
      if (progressInfoBuilder_ == null) {
        if (progressInfo_ != null) {
          progressInfo_ =
            cn.com.unary.initcopy.grpc.entity.ProgressInfo.newBuilder(progressInfo_).mergeFrom(value).buildPartial();
        } else {
          progressInfo_ = value;
        }
        onChanged();
      } else {
        progressInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public Builder clearProgressInfo() {
      if (progressInfoBuilder_ == null) {
        progressInfo_ = null;
        onChanged();
      } else {
        progressInfo_ = null;
        progressInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder getProgressInfoBuilder() {
      
      onChanged();
      return getProgressInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    public cn.com.unary.initcopy.grpc.entity.ProgressInfoOrBuilder getProgressInfoOrBuilder() {
      if (progressInfoBuilder_ != null) {
        return progressInfoBuilder_.getMessageOrBuilder();
      } else {
        return progressInfo_ == null ?
            cn.com.unary.initcopy.grpc.entity.ProgressInfo.getDefaultInstance() : progressInfo_;
      }
    }
    /**
     * <pre>
     *进度信息
     * </pre>
     *
     * <code>optional .cn.com.unary.initcopy.grpc.entity.ProgressInfo progressInfo = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.com.unary.initcopy.grpc.entity.ProgressInfo, cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder, cn.com.unary.initcopy.grpc.entity.ProgressInfoOrBuilder> 
        getProgressInfoFieldBuilder() {
      if (progressInfoBuilder_ == null) {
        progressInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.com.unary.initcopy.grpc.entity.ProgressInfo, cn.com.unary.initcopy.grpc.entity.ProgressInfo.Builder, cn.com.unary.initcopy.grpc.entity.ProgressInfoOrBuilder>(
                getProgressInfo(),
                getParentForChildren(),
                isClean());
        progressInfo_ = null;
      }
      return progressInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.com.unary.initcopy.grpc.entity.TaskState)
  }

  // @@protoc_insertion_point(class_scope:cn.com.unary.initcopy.grpc.entity.TaskState)
  private static final cn.com.unary.initcopy.grpc.entity.TaskState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.unary.initcopy.grpc.entity.TaskState();
  }

  public static cn.com.unary.initcopy.grpc.entity.TaskState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskState>
      PARSER = new com.google.protobuf.AbstractParser<TaskState>() {
    public TaskState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskState> getParserForType() {
    return PARSER;
  }

  public cn.com.unary.initcopy.grpc.entity.TaskState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

