// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy.proto

package cn.com.unary.initcopy.grpc;

public final class IC_Service {
  private IC_Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017init_copy.proto\022\032cn.com.unary.initcopy" +
      ".grpc\032\026init_copy_entity.proto2\252\003\n\010InitCo" +
      "py\022c\n\003Add\022+.cn.com.unary.initcopy.grpc.e" +
      "ntity.SyncTask\032-.cn.com.unary.initcopy.g" +
      "rpc.entity.ExecResult\"\000\022e\n\005Query\022,.cn.co" +
      "m.unary.initcopy.grpc.entity.QueryTask\032," +
      ".cn.com.unary.initcopy.grpc.entity.TaskS" +
      "tate\"\000\022h\n\006Delete\022-.cn.com.unary.initcopy" +
      ".grpc.entity.DeleteTask\032-.cn.com.unary.i" +
      "nitcopy.grpc.entity.ExecResult\"\000\022h\n\006Modi",
      "fy\022-.cn.com.unary.initcopy.grpc.entity.M" +
      "odifyTask\032-.cn.com.unary.initcopy.grpc.e" +
      "ntity.ExecResult\"\000B*\n\032cn.com.unary.initc" +
      "opy.grpcB\nIC_ServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.com.unary.initcopy.grpc.entity.IC_Entity.getDescriptor(),
        }, assigner);
    cn.com.unary.initcopy.grpc.entity.IC_Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
