// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_constant.proto

package cn.com.unary.initcopy.grpc.constant;

/**
 * <pre>
 *压缩类型
 * </pre>
 *
 * Protobuf enum {@code cn.com.unary.initcopy.grpc.constant.CompressType}
 */
public enum CompressType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *不压缩
   * </pre>
   *
   * <code>COMPRESS_NONE = 0;</code>
   */
  COMPRESS_NONE(0),
  /**
   * <pre>
   *使用zlib压缩
   * </pre>
   *
   * <code>COMPRESS_ZLIB = 1;</code>
   */
  COMPRESS_ZLIB(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *不压缩
   * </pre>
   *
   * <code>COMPRESS_NONE = 0;</code>
   */
  public static final int COMPRESS_NONE_VALUE = 0;
  /**
   * <pre>
   *使用zlib压缩
   * </pre>
   *
   * <code>COMPRESS_ZLIB = 1;</code>
   */
  public static final int COMPRESS_ZLIB_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CompressType valueOf(int value) {
    return forNumber(value);
  }

  public static CompressType forNumber(int value) {
    switch (value) {
      case 0: return COMPRESS_NONE;
      case 1: return COMPRESS_ZLIB;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CompressType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CompressType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CompressType>() {
          public CompressType findValueByNumber(int number) {
            return CompressType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.constant.IC_Constant.getDescriptor()
        .getEnumTypes().get(1);
  }

  private static final CompressType[] VALUES = values();

  public static CompressType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CompressType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:cn.com.unary.initcopy.grpc.constant.CompressType)
}

