// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: init_copy_constant.proto

package cn.com.unary.initcopy.grpc.constant;

/**
 * <pre>
 *同步方式
 * </pre>
 *
 * Protobuf enum {@code cn.com.unary.initcopy.grpc.constant.SyncType}
 */
public enum SyncType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *全同步
   * </pre>
   *
   * <code>SYNC_ALL = 0;</code>
   */
  SYNC_ALL(0),
  /**
   * <pre>
   *根据修改时间比较
   * </pre>
   *
   * <code>SYNC_TIME_DIFF = 1;</code>
   */
  SYNC_TIME_DIFF(1),
  /**
   * <pre>
   *计算hash，同步不同的块
   * </pre>
   *
   * <code>SYNC_DATA_DIFF = 2;</code>
   */
  SYNC_DATA_DIFF(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *全同步
   * </pre>
   *
   * <code>SYNC_ALL = 0;</code>
   */
  public static final int SYNC_ALL_VALUE = 0;
  /**
   * <pre>
   *根据修改时间比较
   * </pre>
   *
   * <code>SYNC_TIME_DIFF = 1;</code>
   */
  public static final int SYNC_TIME_DIFF_VALUE = 1;
  /**
   * <pre>
   *计算hash，同步不同的块
   * </pre>
   *
   * <code>SYNC_DATA_DIFF = 2;</code>
   */
  public static final int SYNC_DATA_DIFF_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SyncType valueOf(int value) {
    return forNumber(value);
  }

  public static SyncType forNumber(int value) {
    switch (value) {
      case 0: return SYNC_ALL;
      case 1: return SYNC_TIME_DIFF;
      case 2: return SYNC_DATA_DIFF;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SyncType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SyncType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SyncType>() {
          public SyncType findValueByNumber(int number) {
            return SyncType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return cn.com.unary.initcopy.grpc.constant.IC_Constant.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final SyncType[] VALUES = values();

  public static SyncType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SyncType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:cn.com.unary.initcopy.grpc.constant.SyncType)
}

